### ISSUE TITLE
Asnyc outside of the `model` hook

### ISSUE THREAD

**Issue by danmcclain** [ember-fastboot/ember-cli-fastboot#122]
Per the discussion on the FastBoot hangout today, adding an issue to track:

> - [ ] Design API for deferring FastBoot flush to the server (via pushing promises to the service, or something else)
>   - [ ] Take into account that you should probably wait for the next render after the asynchrony

Things to consider:  
 - [ ] Approach for blocking page render 
 - [ ] Ember-data async relationships

**Comment by tomdale** [comment]
I think the endgame here is something we've been referring to in core team discussions as async components, which are related to routable components. That feature needs careful design, though, so I'm wondering if there's a small, scoped addition to FastBoot we could offer that serves purely as a signal to FastBoot to defer rendering.

**Comment by danmcclain** [comment]
This is done with `deferRendering`
