### ISSUE TITLE
Ember-data custom headers not included in requests

### ISSUE THREAD

**Issue by paulelliott** [ember-fastboot/ember-cli-fastboot#125]
I have a headers object defined in my ember-data adapter but they are not being sent with the requests to my API server. When I run the app without fastboot they are sent as expected but with fastboot they are omitted.

ember 2.3.1
ember-data 2.4.0-beta.3+8d22d1095e
ember-cli-fastboot 0.5.0

**Comment by kratiahuja** [comment]
The custom headers are actually included and run as part of `beforeSend` hook of jquery ajax /najax (in case of fastboot) (see: https://github.com/emberjs/data/blob/v2.4.0/addon/adapters/rest.js#L918).

As part of najax(), the header property is set by calling the `beforeSend()` (see here: https://github.com/najaxjs/najax/blob/master/lib/najax.js#L75). 

I confirmed this using http-mock and running the app in fastboot. 

I think this can be closed.
