### ISSUE TITLE
API for instrumentations

### ISSUE THREAD

**Issue by musaffa** [ember-fastboot/ember-cli-fastboot#129]
As asked in the Global Ember Meetup, FastBoot should expose some API so that app analytics engines can collection data for instrumentation, for example,

1) application boot up time
2) request queue times
3) application instance initialization times
4) the response latency of external services
5) render times
6) overall response time per route
7) memory and object allocations on boot up and per instance initialization etc.

**Comment by tomdale** [comment]
This would actually be a great addition to Ember itself, I think. I want to know these things for more than just FastBoot. :)

**Comment by stefanpenner** [comment]
ya i agree with @tomdale, lets open this over at https://github.com/ember-best-practices/ember-perf-timeline and ensure that effort also supports fastboot!
