### ISSUE TITLE
Using app.import for browser-only packages

### ISSUE THREAD

**Issue by BenKingBBC** [ember-fastboot/ember-cli-fastboot#134]
At the minute, it doesn't look like I can conditionally use `app.import` based on whether I'm building for the FastBoot build, or the browser build.

I'm trying to import a bower package that I'm only utilising inside `didInsertElement`.

**Comment by rwjblue** [comment]
You can use `process.env.EMBER_CLI_FASTBOOT` flag during your build process for conditionals.

This is set inside the `ember fastboot:build` command here: https://github.com/tildeio/ember-cli-fastboot/blob/master/lib/commands/fastboot-build.js#L13.

**Comment by BenKingBBC** [comment]
I've tried doing a conditional check against `process.env.EMBER_CLI_FASTBOOT`, but it appears that that applies for both the server-rendered app and the browser build. The app boots successfully, but on the client the JS starts throwing errors that the libraries do not exist.

Unless I am building the app wrong? With a clean directory I'm running `ember fastboot --serve-assets`.

**Comment by zacksiri** [comment]
i can confirm this as well, having the same issue.

**Comment by zacksiri** [comment]
managed to figure it out 

```javascript
  if ((process.env.EMBER_CLI_FASTBOOT !== 'true')) {
    app.import('bower_components/bootstrap-sass/assets/javascripts/bootstrap.js');
  }
```

**Comment by tomdale** [comment]
@zacksiri Would you mind submitting a PR to the documentation? https://github.com/ember-fastboot/fastboot-website

**Comment by danmcclain** [comment]
Documented in the [README](https://github.com/ember-fastboot/ember-cli-fastboot#disabling-incompatible-dependencies), website is outdated compared to the README, and is on the radar of the FastBoot team

**Comment by devdemi** [comment]
Please help turn off addons which specific for browser.
I have addon ember-fullcalendar in index.js of this addon next code

> module.exports = {
>   name: 'ember-fullcalendar',
> 
>   included: function(app) {
> 
>     app.import(app.bowerDirectory + '/fullcalendar/dist/fullcalendar.js');
>     app.import(app.bowerDirectory + '/fullcalendar/dist/fullcalendar.css');
> 
>     // Add scheduler to executable unless configured not to.
>     if (!app.options ||
>         !app.options.emberFullCalendar ||
>         app.options.emberFullCalendar.scheduler === undefined || app.options.emberFullCalendar.scheduler) {
>       app.import(app.bowerDirectory + '/fullcalendar-scheduler/dist/scheduler.js');
>       app.import(app.bowerDirectory + '/fullcalendar-scheduler/dist/scheduler.css');
>     }
>   }
> };

So Do I need to make fork of this addon to check environment `process.env.EMBER_CLI_FASTBOOT` or Ember-cli allows to figure out in another way?

**Comment by danmcclain** [comment]
Yes, the add on needs to be patched to conditionally call the import lines
