### ISSUE TITLE
<img src={{model.src}} /> seems to make Najax sad

### ISSUE THREAD

**Issue by hhff** [ember-fastboot/ember-cli-fastboot#150]
I've been working all `#Emberconf2016` to try and get my addon, ember-infinity to be fastbootable, and I finally found the reason why my Fastboot server has been choking and dying on every request with this error:

```
  ember-cli-fastboot:server middleware request; path=/ +18m
  ember-cli-fastboot:server handling url; url=/ +0ms
url.js:110
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:110:11)
    at Object.urlParse [as parse] (url.js:104:5)
    at IncomingMessage.<anonymous> (/Users/hhff/dev/Ember/fastbootize/fastboot-find-all/node_modules/ember-cli-fastboot/node_modules/ember-fastboot-server/node_modules/najax/lib/najax.js:175:40)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
``` 

This bug can be seen here (works with `ember s`, dies with `ember fastboot --serve-assets`:
https://github.com/hhff/fastboot-img-src-bug

I'm using the Spotify API to load 20 albums from alternative electronic artist, Squarepusher.

When I remove [this line](https://github.com/hhff/fastboot-img-src-bug/blob/master/app/templates/application.hbs#L2), the app Fastboots nicely.

---
In other news, pretty sure this means that ember-infinity has always been Fastboot compatible :nail_care:

**Comment by kratiahuja** [comment]
Probably a dumb question (or maybe I don't have too much context into Fastboot implementation yet).

Did you try hardcoding the src to a string instead of reading from model.src? Did that work correctly for you?

If so, I think simple-dom should have transformed it to a string right ? (in which case this doesn't look like an najax issue)

**Comment by taras** [comment]
@hhff I had the same problem. I fixed it by wrapping the src in quotes, ie:

`<img src="{{model.src}}" />` it should still work properly even as  a string.

**Comment by tomdale** [comment]
@hhff I believe this has been fixed in the latest beta, can you confirm?

**Comment by hhff** [comment]
confirmed fixed - thanks @tomdale & @taras !
