### ISSUE TITLE
Cannot read property 'createTextNode' of undefined

### ISSUE THREAD

**Issue by mako87** [ember-fastboot/ember-cli-fastboot#152]
`ember fastboot`

`Cannot read property 'createTextNode' of undefined`
`TypeError: Cannot read property 'createTextNode' of undefined`

`at /Users/Marco/Developer/risflow-client/fastboot-dist/fastboot/bower_components/interact/interact.js:17:1`
    
`at /Users/Marco/Developer/risflow-client/fastboot-dist/fastboot/bower_components/interact/interact.js:29:1`

`at /Users/Marco/Developer/risflow-client/fastboot-dist/fastboot/bower_components/interact/interact.js:5920:1`

**Comment by tomdale** [comment]
@mako87 It looks like the interact component is assuming a DOM exists when it starts up. You will probably want to not `app.import` this in your build file when running in FastBoot mode (look for `process.env.EMBER_CLI_FASTBOOT`).
