### ISSUE TITLE
git dep may cause issues for our firewall'd users

### ISSUE THREAD

**Issue by stefanpenner** [ember-fastboot/ember-cli-fastboot#156]
chai-fs

**Comment by tomdale** [comment]
This was abandonware for 2 years but looks like the chaijs org is picking it up, will switch to npm version as soon as its done: https://github.com/chaijs/chai-fs/issues/10

**Comment by tomdale** [comment]
Looks like the new version has not been released yet; still waiting on that.

**Comment by stefanpenner** [comment]
looks addressed
