### ISSUE TITLE
Syntax error when closure actions are interpreted

### ISSUE THREAD

**Issue by mike-north** [ember-fastboot/ember-cli-fastboot#162]
When the inline javascript fastboot puts in place up for closure actions is parsed, chrome complains about a syntax error.

## Failing Case

**app/components/x-thing.js**
```js
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    myAction() {
      alert('hello');
    }
  }
});

```
**app/templates/components/x-thing.hbs**
```hbs
<label onclick={{action 'myAction'}}>
  Click Me
</label>
```
Here's what the DOM ends up looking like as it comes over the wire
```html
<label onclick="function () {
        for (var _len2 = arguments.length, args = Array(_len2), _key2 = 0; _key2 < _len2; _key2++) {
          args[_key2] = arguments[_key2];
        }

        if (valuePath &amp;&amp; args.length > 0) {
          args[0] = _emberMetalProperty_get.get(args[0], valuePath);
        }

        return _emberMetalRun_loop.default.join.apply(_emberMetalRun_loop.default, [target, action].concat(args));
      }">Click Me</label>
```

Chrome complains with
```
Uncaught SyntaxError: Unexpected token ((…)
```

I don't believe the body of the function is the problem here, as we can reproduce this same issue in a very simple (pure HTML) scenario. For example, this is not valid
```html
<p onclick="function() {alert('hello');};">Click me</p>
```
but of course this will work as expected
```html
<p onclick="alert('hello');">Click me</p>
```
and so will this (and we get the closure that's important to ember)
```html
<p onclick="(function() {alert('hello');}());">Click me</p>
```

**Comment by rwjblue** [comment]
This is similar in concept to https://github.com/ember-fastboot/ember-cli-fastboot/issues/161. simple-dom is currently just `toString`ing attributes, which results in the function being inlined like this.

**Comment by stefanpenner** [comment]
the root issue is https://github.com/tildeio/htmlbars/blob/master/packages/dom-helper/lib/prop.js#L11 assumes Element is a real element  SimpleDOM is not, which makes this a tad trickier., and set the callback as an attribute rather then a prop.

**Comment by tomdale** [comment]
This should be fixed in the latest betas.
