### ISSUE TITLE
Support for conditionally including vendored assets in `ember-cli-build.js`

### ISSUE THREAD

**Issue by danmcclain** [ember-fastboot/ember-cli-fastboot#167]
There is currently no way to conditionally include/exclude scripts (like jquery plugins) that are imported via `app.import` in `ember-cli-build.js` at this time, the flag set by running `ember fastboot` (`EMBER_CLI_FASTBOOT`) is not present at build time

**Comment by rwjblue** [comment]
An environment variable isn't going to cut it in this context.  We are actually doing two builds now, right?

**Comment by danmcclain** [comment]
Confirm

**Comment by mike-north** [comment]
Just curious, but is [this approach](https://github.com/levanto-financial/ember-materialize-shim/blob/b929b449db1740e650737394fc30bc2e3f78ecb4/index.js#L24-L26) inappropriate for a vendor (or bower) dependency that __needs__ jQuery at script-evalutation time? 

**./index.js**
```js
module.exports = {
  included: function(app) {
    this._super.included(app);
    
    if (!process.env.EMBER_CLI_FASTBOOT) {
      app.import(app.bowerDirectory + '/materialize/dist/js/materialize.js');
    }
  }
};
```

**Comment by danmcclain** [comment]
This works in addons (I just did the same for ember-cli-sticky), but for your application's `ember-cli-build.js`, the file is only evaluated once, prior to the flag being set. I thought this was going to be an issue for the app I am working on, but at this point it is not. But I can see this being an issue for applications in the future depending on what applications import

**Comment by andressrg** [comment]
I'm experiencing this issue in my app. 

I do things like:
```
  if (!process.env.EMBER_CLI_FASTBOOT) {
    app.import(app.bowerDirectory + '/localforage/dist/localforage.js');
    app.import(app.bowerDirectory + '/jquery.payment/lib/jquery.payment.js');
  }
```

in the `ember-cli-build.js` file. This worked on `ember-cli-fastboot` 0.5.0 but not on 0.6.2.

What is the correct way to do it now? Wrap those imports on ember cli addons?

**Comment by danmcclain** [comment]
I think #145 will fix this

**Comment by tomdale** [comment]
This should work now
