### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by t4t5** [ember-fastboot/ember-cli-fastboot#172]
So far I've worked around all the 3rd party libraries that try to access DOM elements, but this seems rather weird since it's from the Ember.js library, which I assume should work well with Fastboot?

As soon as I visit my browser page, I get an internal server error and this message is logged:

```
Ember FastBoot running at http://[::]:3000
ReferenceError: document is not defined
    at new DOMHelper (/Users/Tristan/dev/my-project/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:3209:1)
    at DOMHelper.EmberDOMHelper (/Users/Tristan/dev/my-project/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:12347:1)
```

Have I missed anything? I'm running Ember CLI 2.4.3 with Ember.js 2.4.3 and Fastboot 0.6.2.

**Comment by mansona** [comment]
I'm getting the same issue and it doesn't seem to be within any third party code, it seems to be in the fastboot vendor code. Here it is in the node debugger: 

![screen shot 2016-04-20 at 15 14 43](https://cloud.githubusercontent.com/assets/594890/14677727/b4bc593c-070a-11e6-8e0c-9a8b1a732e16.png)

any suggestions to debug? if you need me to try anything else out just let me know. 

Here is the output of my `ember -v`: 

```
➜  website git:(feature/googleAnalytics) ✗ ember -v
version: 2.4.2
node: 4.2.1
os: darwin x64```

**Comment by rwjblue** [comment]
From the screenshot that looks like `tether` code not fastboot itself, [see here](https://github.com/HubSpot/tether/blob/v1.0.0/src/js/tether.js#L24-L34).  Good news though, it is fixed in tether 1.2.0 ([see here](https://github.com/HubSpot/tether/blob/v1.2.0/src/js/tether.js#L24-L37)).

**Comment by mansona** [comment]
@rwjblue perfect, thanks for the info 👍  Assuming that my issue was the same as @t4t5 I assume this issue should be closed now?

**Comment by rwjblue** [comment]
Well, every instance of `document is not defined` is likely to be a different thing (or at least potentially is).

**Comment by rwjblue** [comment]
But I agree, there isn't much we can do from a generic case AFAICT.

I'm going to close for now, @tomdale/@danmcclain please reopen if you disagree...

**Comment by tomdale** [comment]
@rwjblue :+1: Nothing we can do AFAIK in the generic case, but I want to write a guide to help people diagnose these issues.

**Comment by mansona** [comment]
@tomdale I think the guide you wrote already showing how to get the system running in the node-inspector should be 90% the way towards guiding people to what they need. I didn't make the link that my issue was in the vendor file, hence a third party dependency so something that warns against that might be helpful 👍
