### ISSUE TITLE
Fastboot leaks Ember tests out of the testing container

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#174]
It appears that Fastboot is forcing `.ember-application` onto the `body` tag regardless of any `rootElement` overrides that may exist in the application configuration. This causes the `/tests` from an Ember application to leak out of the test container.

**Comment by bcardarella** [comment]
Digging down into this...

This appears to happen because the test environment config is injected into the `index.html` as a meta tag. However, Fastboot is wiping out that meta tag and the test environment's config is never present so the application falls back to the default config.

**Comment by tomdale** [comment]
How were you running the tests?

**Comment by bcardarella** [comment]
Hitting `/tests` when running the development server. I can get around this by using `ember test --server`

It brings up a larger question of if this would be considered an actual bug. Should ember-cli enforce the test suite through `ember test --server` instead if Fastboot is going to remove meta tags.

**Comment by rwjblue** [comment]
When we remove `storeConfigInMeta: true`, this should be fixed.

> It brings up a larger question of if this would be considered an actual bug. Should ember-cli enforce the test suite through ember test --server instead if Fastboot is going to remove meta tags.

IMO, we should stop adding `/tests` to `ember serve` and always suggest/force usage of `ember test` or `ember test --server`. There are many addons that do things conditionally based on environment at build time, and any of those also muck up running tests from `ember s` and `/tests`.

**Comment by rwjblue** [comment]
The config issue is being tracked in https://github.com/ember-fastboot/ember-cli-fastboot/issues/160.

**Comment by bcardarella** [comment]
> IMO, we should stop adding /tests to ember serve and always suggest/force usage of ember test or ember test --server.

Agreed. My usage of `/tests` is more a legacy reflex than anything. I can open an issue in ember-cli about this.

**Comment by stefanpenner** [comment]
> My usage of /tests is more a legacy reflex than anything

Nah this is totally not legacy.

**Comment by bcardarella** [comment]
@stefanpenner now I'm confused, which way should we go? Seems like you're in favor of keeping `/tests` in the development server?
