### ISSUE TITLE
CSRF attack mitigation

### ISSUE THREAD

**Issue by maletor** [ember-fastboot/ember-cli-fastboot#191]
As an idea, what do you think about implementing a CSRF token feature for Fastboot? Lots of people will want to authenticate their Fastboot Ember apps and all that do will need to use a cookie which necessitates a CSRF token to block malicious websites from making requests.

Related issue: https://github.com/simplabs/ember-simple-auth/issues/944#issuecomment-218244374

**Comment by danmcclain** [comment]
You can prevent CSRF without a CSRF token, I recently wrote an article on it here: https://dockyard.com/blog/2016/03/31/announcing-verify-origin

You'd have to coordinate FastBoot with your API application to use CSRF tokens, as the API application would need to know about/set the token for each user

**Comment by maletor** [comment]
That's awesome. I did not know about `Origin`. Great write up.

**Comment by maletor** [comment]
If your application uses CORS exclusively and explicitly whitelisted trusted domains, I don't think CSRF would be an issue. Because, while the cookies may be sent, the request itself will be rejected. Still, there are probably lots of apps that wildcard CORS or use proxies on the same origin to reach the API.

**Comment by maletor** [comment]
@danmcclain, how are you planning on using the `Origin` header to validate same origin requests. The spec only specifies that same origin requests MAY use the header so in theory your origin check would need to either not expect the `Origin` header or, if present, check it matches a whitelist.
