### ISSUE TITLE
Cannot read property 'destroy' of undefined visiting any route

### ISSUE THREAD

**Issue by IAmJulianAcosta** [ember-fastboot/ember-cli-fastboot#209]
Hi, I'm implementing Fastboot in an existing project, but I just can't visit any route, here is my stacktrace:

```
TypeError: Cannot read property 'destroy' of undefined at /home/julian/gc/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/ember-app.js:226:30 
at /home/julian/gc/dist/fastboot/vendor.js:67087:36
at tryCatch  (/home/julian/gc/dist/fastboot/vendor.js:64860:14)
at invokeCallback (/home/julian/gc/dist/fastboot/vendor.js:64875:15)
at publish  (/home/julian/gc/dist/fastboot/vendor.js:64843:9)
at /home/julian/gc/dist/fastboot/vendor.js:43399:7
at Queue.invoke (/home/julian/gc/dist/fastboot/vendor.js:11650:16)
at Object.Queue.flush (/home/julian/gc/dist/fastboot/vendor.js:11714:11) 
at Object.DeferredActionQueues.flush (/home/julian/gc/dist/fastboot/vendor.js:11522:17)
at Object.Backburner.end (/home/julian/gc/dist/fastboot/vendor.js:11877:25) 
```

I'm using ember 2.5.1 and fastboot 1.0.0-beta.2

---

Ok, I have to edit this issue, found the error. When `buildAppInstance` is called, it [executes ](https://github.com/ember-fastboot/fastboot/blob/master/lib/ember-app.js#L173)`this.app.boot()`, and if promises rejects, there isn't nothing that tells the dev that app booting failed. 

I tried to add a `catch` to the promise, but it only gives a very small information about what failed in the app booting process (in my case, `L is undefined`, I was using Leaflet), but I had zero clues about where was the error ocurring, because the error returned was only a String, but without stacktrace. 

And my original error was that `finally` [function ](https://github.com/ember-fastboot/fastboot/blob/master/lib/ember-app.js#L226)called in `buildAppInstance` tries to destroy a non existant instance, generating the stacktrace I generated.

Temporary workaround: Reproducing fastboot environment in ember and debug using browser. But would be nice if we have more information about why booting an appfails.

**Comment by tomdale** [comment]
@IAmJulianAcosta Wow, thank you for catching that and tracking it down!

I'm not familiar with Leaflet, but I'd guess it is detecting that it's not in a browser environment and thus not exporting the `L` global.

We should definitely add a `catch()` clause here to catch the error. Are you able to submit a PR? Once we have that, we can investigate if there is a way to get a better stack trace.
