### ISSUE TITLE
CSS Updates cause page reload (navigation) instead of hot reload

### ISSUE THREAD

**Issue by rjfranco** [ember-fastboot/ember-cli-fastboot#212]
When ember-cli-fastboot is included in a project, css updates cause a page refresh, not sure where in particular this originates, can be reproduced in a new 2.6.1 project where the only step taken is running `ember install ember-cli-fastboot`

**Comment by tomdale** [comment]
I'm not familiar with how CSS hot reloading works in Ember CLI or how we might be interfering with it. That said, I think once we integrate better into the Ember CLI build pipeline by using public hooks (and avoiding a double build of the app) this should hopefully get resolved.

**Comment by stefanpenner** [comment]
@tomdale css hot-reloading, diffs the output of the build, and reports all changed paths via websocket to livereload.js. If hot-reloading is broken, it is most likely because fast-boot causes everything to invalidate/rebuild and change.

**Comment by stefanpenner** [comment]
For reference, the relevant code in ember-cli  is: here https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/livereload-server.js#L140-L153

**Comment by stefanpenner** [comment]
There is a debug, [here](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/livereload-server.js#L155) So running the following, will help inform further what is up:

```
`DEBUG="ember-cli:live-reload:*" ember <w/e command>`

**Comment by kpfefferle** [comment]
@rjfranco I think this issue can be closed now that #239 has landed. Confirm?
