### ISSUE TITLE
Application route model

### ISSUE THREAD

**Issue by CostaRico** [ember-fastboot/ember-cli-fastboot#213]
Hello, I'd like to get model for application (initial)route directly from database on a server, do you know some ways to implement that or maybe some thoughts? thx a lot!

**Comment by danmcclain** [comment]
You can use Node/NPM dependencies from within FastBoot by [whitelisting them][whitelist]. You'll just want to check for `this.get('fastboot.isFastBoot')` before calling the node code

```
// application/route.js
export default Route.extend({
  fastboot: Ember.inject.service(),
  model() {
    if (this.get('fastboot.isFastBoot')) {
      // Node code here
    }
  }
})
```

[whitelist]: https://github.com/ember-fastboot/ember-cli-fastboot#using-nodenpm-dependencies
