### ISSUE TITLE
Avoid using private API - EmberApp.concatFiles (RFC needed)

### ISSUE THREAD

**Issue by Gaurav0** [ember-fastboot/ember-cli-fastboot#214]
Removing this addon clears many deprecation warnings in Ember CLI 2.7 beta for using EmberApp.concatFiles.

I think there is some private option that allows you to call concatFiles without a deprecation warning.

**Comment by danmcclain** [comment]
FastBoot team needs to address @rwjblue's comment https://github.com/ember-fastboot/ember-cli-fastboot/pull/217#issuecomment-226207533

**Comment by tomdale** [comment]
As noted in #217, we need to write an RFC for adding public hooks to Ember CLI's build pipeline so that this doesn't break again in the future.

**Comment by danmcclain** [comment]
Still need the RFC for `concatFiles`, leaving this open until we do so

**Comment by stefanpenner** [comment]
we are not longer using this API
