### ISSUE TITLE
Deprecation warnings for not calling _super in init

### ISSUE THREAD

**Issue by Gaurav0** [ember-fastboot/ember-cli-fastboot#216]
If your application is using Ember CLI 2.7 beta

**Comment by rwjblue** [comment]
We are not using `init`, it is unlikely that these deprecations are from ember-cli-fastboot.

**Comment by Gaurav0** [comment]
They aren't. They are from the dependency on ember-cli stable, being used in the same app as ember cli beta.

**Comment by rwjblue** [comment]
Cool, I'm going to close this (as there is nothing we can do here). Please open issues for the offending addons as you have time...
