### ISSUE TITLE
Strategies for debugging fastboot

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#224]
Too often have I made a bunch of changes to my app then go and build and fastboot is no longer working. The errors are silent and I end up with a non-fastboot `index.html` with the fastboot placeholders.

This can be a difficult development experience as it seems to happen for several different reasons. Test suites will pass but fastboot fails.

Are there strategies that can be shared for going about debugging this? Rather than having to go back and run a git-bisect on many commits? Even worse, if the I squash my commits assuming that the tests passing is 👍 I lose the fidelity of atomic commits to isolate the problem.

**Comment by danmcclain** [comment]
There are errors logged by the server, the way I've debugged in the past is to find the line number from the error to find the offending code in the vendor or app js file in `dist/fastboot` you can also attach a debugger to the instance of fastboot as well

**Comment by bcardarella** [comment]
As I mentioned, the error is silent and no fastboot page is actually rendered out. Instead I get the regular ember-cli index page but with the fastboot placeholders.

**Comment by danmcclain** [comment]
Is this on the dockyard server? If so, it's because I had it fall back to the static page as to not server the empty page. And since the script running the server is backgrounded, the error messages go into the ether. Updating the script to log to a known file will yield the errors.

**Comment by danmcclain** [comment]
Another option is to add capybara/selenium test that hit a running fastboot server so that CI will catch the failures before production

**Comment by danmcclain** [comment]
I also just remembered that there should be upstart logs somewhere in /var/log
