### ISSUE TITLE
How to force code execution on the Client?

### ISSUE THREAD

**Issue by 256dpi** [ember-fastboot/ember-cli-fastboot#259]
While working on the following PR for Ember Simple Auth, we realized that the OAuth2 Implicit Grant Flow would never work in conjunction with fastboot: https://github.com/simplabs/ember-simple-auth/pull/1057.

> The current implementation will break in conjunction with fastboot as the redirect by the authentication server would always trigger a fastboot server side render that has no access to `window.location.hash` for obtaining the access token.

Is there a way to force the execution of a Route on the client side? Something like a route blacklist or even a deferred execution of code blocks? Or is there another approach that we missed?

**Comment by 256dpi** [comment]
Can somebody please comment on this?

**Comment by danmcclain** [comment]
See "The FastBoot Service" http://ember-fastboot.com/docs/user-guide

You are able to check whether you're running in FastBoot via`this.get('fastboot.isFastBoot')`

**Comment by danmcclain** [comment]
Also you are able to get access to the request details within FastBoot via the service, details in the above link

**Comment by 256dpi** [comment]
@danmcclain Thanks for your response. The problem in this particular case is that the oauth2 access token is passed in the fragment of the request. And as all browsers do not append the fragment when submitting the request it would not be accessible if fastboot is handling the request. Therefore, the authentication callback route logic must be executed/handled in the browser. And as the browser normally redirects to that callback from the authentication server the request would always be handled by fastboot if enabled.

In that sense the only solution I can think of is something like a route blacklist within fastboot.

**Comment by danmcclain** [comment]
You should be able to do what you want by wrapping the browser only code in:

```js
if(!this.get('fastboot.isFastBoot')) {
  // this will only execute in the browser
}
```

**Comment by 256dpi** [comment]
Let's assume the following route mounted at `/facebook-callback` (simplified):

```js
export default Ember.Route({
  activate() {
    // handle authentication by parsing window.location.hash
    // redirect to dashboard if logged in or redirect to login page on error
  }
});
```

In OAuth2, the location is redirected to the authentication server to let the user login:

```
From: https://example.com/sign-in-with-facebook
To: https://facebook.com/oauth2/login?client_id=xxx&scope=xxx&...
``` 

The user then authenticates himself and authorizes the service. The authentication server (facebook) will now redirect back to the callback handler:

```
From: https://facebook.com/oauth2/login?client_id=xxx&scope=xxx&...
To: https://example.com/facebook-callback#access_token=xxx&scope=xxx&...
```

The browser needs to load the Ember Application again and therefore if Fastboot is enabled the requested page will always be pre-rendered by fastboot on the server. However, the access_token (part of the location hash) has never been transmitted to the server by the browser.

I don't see how the snippet you metioned above would be any help in this situation as `this.get('fastboot.isFastBoot')` will always be true and never execute the browser specific code.

The solution I imagine is to tell fastboot that this particular route should not be pre-rendered and therefore fully executed on the client to have access to the access token in the fragment.

**Comment by danmcclain** [comment]
`fastboot.isFastBoot` is only true when ember is executing in node on the server, it will never be true client side in the browser, and is meant for exactly this purpose

If you do the following:

```js
export default Ember.Route({
  activate() {
    if(!this.get('fastboot.isFastBoot')) {
    // handle authentication by parsing window.location.hash
    // redirect to dashboard if logged in or redirect to login page on error
    }
  }
});
```

This should perform as desired, only executing in the browser

**Comment by 256dpi** [comment]
Thanks for your patience. The actual part I missed was that I was not aware that ember would execute the route again in the browser even if it already had rendered in fastboot on the server before. Your snipped makes sense to me now and it is totally the key to the problem. ;)

As a followup question: This means If a fastboot pre-rendered Ember app is loaded in the browser the whole request is executed again as it would without fastboot? Are there any docs about this process?

**Comment by danmcclain** [comment]
Yes, right now, before rehydration has landed, the app will re-execute a second time, you can use fastboot's shoebox to pass server side state to the browser. The addon `ember-data-fastboot` takes care of most of ember-data's interactions and stores the responses in the shoebox to be reused in the client

In terms of documentation, I don't think we have one that outlines the fact that it renders twice currently, but I could be wrong.

**Comment by 256dpi** [comment]
Ok I see, thanks for the additional info.
