### ISSUE TITLE
Fastboot server failing with Ember 2.9

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#265]
I just tried to update dockyard.com to Ember 2.9. Fastboot's server is failing:

```
Installing FastBoot npm dependencies

Build successful - 14519ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 3738ms
Babel                                         | 2054ms
Babel                                         | 1397ms
Babel                                         | 764ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (66)                                    | 10319ms (156 ms)
TemplateCompiler (22)                         | 726ms (33 ms)

Error: ENOTEMPTY: directory not empty, rmdir '/Users/bcardarella/projects/dockyard.com/dist/node_modules/moment/src/'
    at Error (native)
```

App was working with 2.7 just fine. Only changes I made were to bump ember.js from 2.7 -> 2.9.0-beta.2 in bower and ember-data 2.7 -> 2.9.0-beta.1 in npm

I don't know why Fastboot's server would care that moment's `src/` directory is not empty or why it would be attempting to run `rmdir` on it.

Also, a lack of proper stack trace here makes this difficult for me to diagnose. I'm not clear where I should begin.

**Comment by danmcclain** [comment]
Did you upgrade ember-cli-fastboot? The more recent versions have introduced this issue, it's a race condition in the `ember fastboot` command and the fact that it watches now. This is the same issue as https://github.com/ember-fastboot/ember-cli-fastboot/issues/246, which also was the reason 1.0 of FastBoot was pushed back. Closing as duplicate

**Comment by bcardarella** [comment]
Yes, I am on 1.0.0-beta.9

**Comment by bcardarella** [comment]
I also don't think the issues should be closed until it is confirmed as a duplicate

**Comment by danmcclain** [comment]
This only effects the command, and is currently being worked on. This will not effect FastBoot-app-server or building the assets
