### ISSUE TITLE
Is Fastboot Compatible with Engines? 

### ISSUE THREAD

**Issue by ChavaSobreyra** [ember-fastboot/ember-cli-fastboot#267]
I'm trying to build out a basic prototype using engines + fastboot. Fastboot server boots up and works as expected for parent app routes, however when I try to visit a mounted routable engine I get 

```
There was an error trying to run your application in FastBoot.

This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in dist/fastboot/client-b287b72c94449ae895a44166f191b26f.js on line 116.
The exception is probably coming from your app. Look at this file and line number to determine what is triggering the exception.

The full stack trace is:

Failed to load asset manifest. For browser environments, verify the meta tag with name "client/config/asset-manifest" is present. For non-browser environments, verify that you included the node-asset-manifest module.
```

and the referenced block in my client.js:

```
try {
    // If we have a Node version of the asset manifest, use that for FastBoot and
    // similar environments.
    if (require.has(nodeName)) {
      config = require(nodeName)['default']; // eslint-disable-line
    } else {
        var rawConfig = document.querySelector('meta[name="' + metaName + '"]').getAttribute('content');
        config = JSON.parse(unescape(rawConfig));
      }
  } catch (err) {
    throw new Error('Failed to load asset manifest. For browser environments, verify the meta tag with name "' + metaName + '" is present. For non-browser environments, verify that you included the node-asset-manifest module.');
  }
```

In the parent app setting I tried setting storeConfigInMeta: false, but to no avail. 

I'm aware I'm at the bleeding edge of Ember here, but should engines + fastboot work at this point?

**Comment by ChavaSobreyra** [comment]
To report back for anyone who might be having the same issue, engines don't seem to be working through 'ember fastboot --serve-assets' -- the engines pages error out. But engines to appear to serve correctly if you are serving through the ember-fastboot/fastboot-app-server.

¯\_(ツ)_/¯

**Comment by danmcclain** [comment]
Do you have a stacktrace or a sample app? I'm curious what the error is

**Comment by danmcclain** [comment]
Oops, wrong button, sorry!

**Comment by ChavaSobreyra** [comment]
Sure, give me a bit to tear it down into a sample.

**Comment by ChavaSobreyra** [comment]
Here it is: [https://github.com/ChavaSobreyra/fastboot-sample](https://github.com/ChavaSobreyra/fastboot-sample)

**ember serve**
localhost:4200/   <---- Works
localhost:4200/cq-vehicles   <---- Works

**ember fastboot --serve-assets**
localhost:4200/   <---- Works
localhost:4200/cq-vehicles   <---- Errors Out

**using fastboot app server**
localhost:4200/   <---- Works
localhost:4200/cq-vehicles   <---- Fastboot doesn't build html, but app serves and loads successfully. When I updated this issue I mistakenly assumed that it was building HTML correctly. 

Funny thing -- as I tore it down I noticed that with a fresh pull of fastboot-app-server's npm dependencies, it throws a similar error as the fastboot dev server.
` RESILIENT MODE CAUGHT: Error: Could not read config from meta tag with name "cq-vehicles/config/environment" due to error: ReferenceError: document`

I included the server's node_modules pulled earlier this week to illustrate how no error is thrown.  Feel free to rm -rf and pull the latest.

I'm experiencing two other very annoying issues:
ember fastboot --serve-assets is unable to rebuild after first time. I'm forced  to manually clear /dist for each build.
```
fs.js:60
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOTEMPTY: directory not empty, rmdir '/Users/csobreyra/Projects/saas-dev-cq-frontend-node_web_app-/client/dist/node_modules/node-fetch/node_modules/encoding/'
```

Let me know if I did something silly during setup or if I should open issues.

**Comment by danmcclain** [comment]
The rebuild issue is a known issue that I may have time to workaround this weekend

The reason that the app-server still sends HTML is because resilient mode is turned on. 

Those two points aside, if I get some time, I'll poke around and see if I can figure out the issue. I may have an idea if it's looking for the environment, we handle the app environment differently than normal ember. I'm not familiar with the inner working of engines, but I have an idea

**Comment by kratiahuja** [comment]
@ChavaSobreyra I think you might be running into this issue: https://github.com/dgeb/ember-engines/issues/164

**Comment by ChavaSobreyra** [comment]
@danmcclain any luck this weekend? By the way, I'd be happy to take a look at creating a PR myself if you point me in the right direction.

**Comment by ChavaSobreyra** [comment]
@kratiahuja looks like that might be it, however, reading through dgeb/ember-engines#175 sounds like that issue was fixed in v0.2 of engines. I'm using v0.3, and I do see the changes made it into that version, but I'm still having the same issue. Looks like someone else is having the same issue too in [dgeb/ember-engines/issues/193](https://github.com/dgeb/ember-engines/issues/193), so I'll move my discussion over to that thread.

**Comment by danmcclain** [comment]
@ChavaSobreyra I didn;t get a chance this weekend, working on a different fastboot issue right now, hopefully https://github.com/dgeb/ember-engines/pull/175 is where the problem lies. Not sure when I'll get a chance to to peek at this though

**Comment by kratiahuja** [comment]
@ChavaSobreyra We have been using ember-engines v0.3 and it works for us. I don't think this issue is related to fastboot. I would encourage you to open an issue in ember-engines.

**Comment by ChavaSobreyra** [comment]
@danmcclain I did open an issue over at ember-engines: https://github.com/ember-engines/ember-engines/issues/214

Tried to run again today using the latest versiosn of everything, updated my example repo here: https://github.com/ChavaSobreyra/fastboot-sample

Still facing a similar error: 
```Failed to load asset manifest. For browser environments, verify the meta tag with name "client/config/asset-manifest" is present. For non-browser environments, verify that you included the node-asset-manifest module.```

not sure exactly how to proceed...

**Comment by kratiahuja** [comment]
I don't think FastBoot has support for engines (specifically asset-manifest) yet. This [issue](https://github.com/ember-fastboot/ember-cli-fastboot/issues/270) would create a base to allow Engines to work in FastBoot.

cc: @trentmwillis

**Comment by rwjblue** [comment]
> I don't think FastBoot has support for engines (specifically asset-manifest) yet.

_Slight_ correction here: **lazy** ember-engines do not work with FastBoot yet.

**Comment by kratiahuja** [comment]
@rwjblue correct, i forgot the notions in engines :)

**Comment by ChavaSobreyra** [comment]
@rwjblue Thank you for the confirmation! That means this should be working. 

So, given that my engine is non-lazy-loading does that mean there is a bug here? 

What is interesting is that it is failing to find client/config/asset-manifest, but there is indeed an asset manifest under dist/asset-manifest.json. 

Just to recap the error:
```
This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in dist/fastboot/client-b287b72c94449ae895a44166f191b26f.js on line 116.
The exception is probably coming from your app. Look at this file and line number to determine what is triggering the exception.

The full stack trace is:

Failed to load asset manifest. For browser environments, verify the meta tag with name "client/config/asset-manifest" is present. For non-browser environments, verify that you included the node-asset-manifest module.```

and the referenced block:

```
  try {
    // If we have a Node version of the asset manifest, use that for FastBoot and
    // similar environments.
    if (require.has(nodeName)) {
      config = require(nodeName)['default']; // eslint-disable-line
    } else {
        var rawConfig = document.querySelector('meta[name="' + metaName + '"]').getAttribute('content');
        config = JSON.parse(unescape(rawConfig));
      }
  } catch (err) {
    throw new Error('Failed to load asset manifest. For browser environments, verify the meta tag with name "' + metaName + '" is present. For non-browser environments, verify that you included the node-asset-manifest module.');
  }
```

**Comment by ChavaSobreyra** [comment]
Just reading into the error, given that the meta tag and file are present for asset-manifest, does this mean that there is a problem on the ember-cli-fastboot side in regards to the node-asset-manifest module?

**Comment by stefanpenner** [comment]
WIP: https://github.com/ember-engines/ember-engines/pull/418

**Comment by thec0keman** [comment]
It [looks](https://github.com/ember-engines/ember-engines/pull/494) like this can be closed

**Comment by rwjblue** [comment]
Thank you @thec0keman
