### ISSUE TITLE
Target Support in RFC

### ISSUE THREAD

**Issue by tomdale** [ember-fastboot/ember-cli-fastboot#268]
One thing that FastBoot would really benefit from is the first-class notion of "targets" in Ember CLI. Currently there is a notion of "environment," but this is not granular enough to support many use cases.

For example, Ember CLI implicitly assumes that the app is targeting the browser. But there are many other targets that may require different configuration information: FastBoot, Electron, PhoneGap, etc. Each of these likely has a production, development, etc. environment. The configuration information for production browser and production FastBoot likely overlap; therefore, we need the union of `[target, environment]` to capture the full spectrum of different configurations common in Ember development.

This issue is for tracking the development of this feature in Ember CLI so that we may eventually adopt it.
- WIP Targets RFC by myself and @danmcclain: https://gist.github.com/tomdale/537f7cd99ddbb88ddd776378cfea3da9

Note that this WIP RFC has been largely superseded after a discussion I had with @stefanpenner. Hopefully we can jot down the plan of action after this weekend's core team face-to-face meting.

**Comment by martletandco** [comment]
Another thing to consider is the overlap with addons such as [ember-cli-deploy](https://github.com/ember-cli-deploy/ember-cli-deploy), which has a _deploy target_. There may be some confusion if the difference isn't spelt out. I wonder if a different word such a 'platform' or 'type' could replace 'target' here (although those don't seem to fit as nicely).

**Comment by stefanpenner** [comment]
related/complementary https://github.com/ember-fastboot/ember-cli-fastboot/issues/264#issuecomment-252276046

**Comment by stefanpenner** [comment]
I believe we have addressed this on master, by simplifying how fastboot + ember apps work. This doesn't preclude a future of this, but means it is not longer on any critical path
