### ISSUE TITLE
Running fastboot with node-inspector doesn't seem to put fastboot into a running state.

### ISSUE THREAD

**Issue by kitsunde** [ember-fastboot/ember-cli-fastboot#272]
I figured out that node needs to be **<= v6.3.1** because of https://github.com/node-inspector/node-inspector/issues/905

I can run the node-inspector just fine:

``` bash
node-inspector --no-preload
```

I can run fastboot according to the instructions just fine;

``` bash
node_modules/.bin/ember build && node --debug-brk ./node_modules/.bin/ember fastboot --no-build
```

I can open the node inspector and I can resume execution. Then it starts loading all the sources and then nothing else happens. My app is stuck like this:

``` bash
$ node_modules/.bin/ember build && node --debug-brk ./node_modules/.bin/ember fastboot --no-build
Built project successfully. Stored in "dist/".
Debugger listening on [::]:5858
```

Even if I make a completely new app:

``` bash
mkdir embertest
cd embertest
ember init
ember install ember-cli-fastboot
node_modules/.bin/ember build && node --debug-brk ./node_modules/.bin/ember fastboot --no-build
```

This happens on both Ubuntu 14.04 and macOS Sierra.

**Comment by treywood** [comment]
I have the same issue - the FastBoot server doesn't ever start with --no-build or --build=false. If I simply run:

```
ember fastboot --no-build
```

The version number prints, and then the process exits. I created #257 to address this issue - the server waits for a 'postBuild' event to start, and this event is never raised with --no-build

**Comment by kratiahuja** [comment]
`ember fastboot` is now deprecated and `ember serve` now renders your app on server side with ember-cli 2.12.0+. Can you please try again with the instructions here: https://github.com/ember-fastboot/ember-cli-fastboot#developer-tools ? Please open an issue if you still see problems.
