### ISSUE TITLE
Encoded HTML entities in Shoebox data

### ISSUE THREAD

**Issue by steveszc** [ember-fastboot/ember-cli-fastboot#275]
The `Result` of a Fastboot request gets serialized by the `SimpleDOM.HTMLSerializer` before it is sent down to the client (https://github.com/ember-fastboot/fastboot/blob/master/src/result.js). This happens after the Shoebox is appended to the document, and has the unintended consequence of encoding any characters in the shoebox data that happen to be HTML entities. This includes characters such as `&`, `<`, `>`, `"`, `` ` ``, and `'`, which are encoded into `&amp;`, `&lt;`, `&gt;`, `&quot;`, `&#96;` and `&#x27;`, respectively. 

This results in a data payload fetched on the server and stored in the Shoebox to be different than the same data payload fetched on the client. This can cause issues when rendering any data provided by the Shoebox since Ember's rendering layer treats these encoded HTML entities as strings rather than HTML. For example my API may return `Broadway & 1st Ave`, but if that data is fetched on the server and passed to the client in the Shoebox it will be provided as `Broadway &amp; 1st Ave`.

Seems like the `shoebox#retrieve` method ought to have a step that decodes any of these entities before the data is passed to the application.

**Comment by danmcclain** [comment]
This is tracked on https://github.com/ember-fastboot/fastboot via issue 75 https://github.com/ember-fastboot/fastboot/issue/75 and has a PR https://github.com/ember-fastboot/fastboot/pull/85

**Comment by steveszc** [comment]
Sorry I hadn't seen that Issue and PR. I think theres still an issue at play here that I haven't seen addressed.

It seems like there should be an idiomatic way to unescape these characters once they are fetched from the shoebox in the client. Characters `&`, `<`, and `>` will commonly occur in text data stored in the shoebox. When normally consumed from a REST API or other data source they won't be escaped and will display normally in a template, but when consumed from the shoebox they will be escaped and won't display correctly. This seems like a source of frustration and bugs. It seems like the escaping/unescaping of the shoebox content should be transparent to the developer and happen behind the scenes within the `shoebox#retrieve` method.

This, however, may conflict with shoebox content where the original data had escaped entities that shouldn't actually be unescaped. Considering this, maybe it makes more sense to leave it up to the developer to unescape shoebox content as needed. If so, this should be mentioned in the docs, and maybe there ought to be a standard/idiomatic way to do the unescaping such as an alternate method to `shoebox#retrieve` that unescapes the content.

**Comment by danmcclain** [comment]
Would you mind making this comment over on FastBoot? Thanks! Was more directing the conversation over to there to keep it in one place

**Comment by danmcclain** [comment]
Valid points for sure!

**Comment by danmcclain** [comment]
I'm going to paste your comments on the other issue

**Comment by rwjblue** [comment]
> It seems like there should be an idiomatic way to unescape these characters once they are fetched from the shoebox in the client. Characters &, <, and > will commonly occur in text data stored in the shoebox. When normally consumed from a REST API or other data source they won't be escaped and will display normally in a template, but when consumed from the shoebox they will be escaped and won't display correctly.

This is untrue the [JSON spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) states:

> Any code point may be represented as a hexadecimal number. The meaning of such a number is determined by ISO/IEC 10646. If the code point is in the Basic Multilingual Plane (U+0000 through U+FFFF), then it may be represented as a six-character sequence: a reverse solidus, followed by the lowercase letter u, followed by four hexadecimal digits that encode the code point. Hexadecimal digits can be digits (U+0030 through U+0039) or the hexadecimal letters A through F in uppercase (U+0041 through U+0046) or lowercase (U+0061 through U+0066). So, for example, a string containing only a single reverse solidus character may be represented as "\u005C".

It goes on to give the following example:

> The following four cases all produce the same result:
>  * "\u002F"
>  * "\u002f"
>  * "\/"
>  * "/" 

More to the point (and less stupid spec language to read), both of the following results in exactly same parsed object:

```js
{"nastyScriptCase":"<script>alert('owned');</script></script></script>"}
```

```js
{"nastyScriptCase":"\u003cscript\u003ealert('owned');\u003c/script\u003e\u003c/script\u003e\u003c/script\u003e"}
```

Demo can be found here: http://jsbin.com/jojalo/edit?html,js,output

**Comment by steveszc** [comment]
@rwjblue I think the Shoebox escaping that is referenced in PR ember-fastboot/fastboot#85 and the issue I brought up here and in [ember-fastboot/fastboot#78](https://github.com/ember-fastboot/fastboot/issues/78) aren't really all that related.

The [SimpleDom HTML Serializer](https://github.com/ember-fastboot/simple-dom/blob/80ecb549cee039de4977257e0e946c21734bf4b6/lib/simple-dom/html-serializer.js#L46-L57) that Fastboot uses to Serialize the HTML page is escaping all `&`, `<`, and `>` characters, including characters in the Shoebox json. At some point these characters need to be unescaped so that they render correctly on client. I guess the question is whether Fastboot is responsible for this, or the developer is responsible to do it.

Discussion on this should probably continue on [ember-fastboot/fastboot#78](https://github.com/ember-fastboot/fastboot/issues/78)

**Comment by rwjblue** [comment]
Hmm, that serializer shouldn't actually be used for shoebox data after https://github.com/ember-fastboot/fastboot/pull/85 landed. It should be using [this one](https://github.com/ember-fastboot/simple-dom/blob/80ecb549cee039de4977257e0e946c21734bf4b6/lib/simple-dom/html-serializer.js#L63) (`createRawHTMLSection`) as of https://github.com/ember-fastboot/fastboot/pull/85 ([see here](https://github.com/ember-fastboot/fastboot/blob/904f30da8e46c5ad0d5ccd7f342e67454086f362/src/ember-app.js#L316)).

**Comment by steveszc** [comment]
Ahhh that makes sense, thanks!
