### ISSUE TITLE
unify app `fastbootDependencies` and addon `fastBootDependencies`

### ISSUE THREAD

**Issue by kellyselden** [ember-fastboot/ember-cli-fastboot#277]
I got tripped up by the different casing. App uses `fastbootDependencies` [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/2e913eb907d3a8aa2b64d87b2877704a365fa6bf/lib/broccoli/fastboot-config.js#L83) and addon uses `fastBootDependencies` [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/2e913eb907d3a8aa2b64d87b2877704a365fa6bf/lib/broccoli/fastboot-config.js#L185).
We should decide the correct casing and unify them.

**Comment by danmcclain** [comment]
The second one should be corrected. The casing should be, if the `f` is lower, the `b` is also lower, if the `F` is upper then the `B` is

```
Correct:
FastBoot
fastboot
isFastBoot
fastbootDependencies

Incorrect:
Fastboot
fastBoot
isFastboot
fastBootDependencies
```

I don't know if we call this out anywhere, but that is the guideline
