### ISSUE TITLE
In Ember 2.7+ assets should be served from a rootURL-prefixed path

### ISSUE THREAD

**Issue by kfoisy** [ember-fastboot/ember-cli-fastboot#279]
In Ember 2.7+, using the baseURL has been deprecated (see http://emberjs.com/blog/2016/04/28/baseURL.html) and the assets should be served from a rootURL prefixed path.

**Comment by kfoisy** [comment]
I've submitted a pull request for this here: https://github.com/ember-fastboot/ember-cli-fastboot/pull/273

**Comment by kfoisy** [comment]
@danmcclain @rwjblue Can I get any feedback on this issue/pull request? Are there any additional changes I need to make here?

**Comment by kratiahuja** [comment]
hey @kfoisy sorry for the delay here. We have been re-working the entire build and serving pipeline for FastBoot. We recommend to use `ember serve` and `ember fastboot` is now deprecated and will be removed in rc builds. Closing this.
