### ISSUE TITLE
YUIDoc for a dependency is crashing the build

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#285]
ember-cli-fastboot: 1.0.0.beta-11
ember 2.10.0-beta.1

When running `ember fastboot --serve-assets` after a rebuild the following crash happens:

```
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: Error: ENOTEMPTY: directory not empty, rmdir '/Users/****/work/****/dist/node_modules/moment/src/'
    at Error (native)
error: --------------------------------------------------------------------------
error: Node.js version: v5.7.1
error: YUI version: 3.18.1
error: YUIDoc version: 0.10.2
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
```

if I `rm -rf` `dist/node_modules` I can build again. But when I kill the server and attempt to rebuild this error consistently happens.

**Comment by rwjblue** [comment]
YUIDoc is likely just handling any uncaught exceptions (which seems kinda silly to me), see [here](https://github.com/yui/yuidoc/blob/193a7d200ed555fcea6e75a659fab1d0d49e3ee2/lib/index.js#L52-L75).  The issue is likely the same as various other ones reported where `dist/node_modules` isn't properly cleared, and not related to YUIDoc at all.

Others can confirm that though...

**Comment by laantorchaweb** [comment]
I had the same issue only with YUIDoc, I removed that dependency to make it work (trying to upgrade a production app).

**Comment by simonihmig** [comment]
https://github.com/cibernox/ember-cli-yuidoc/pull/46 should fix this. At least the confusing yuidoc logging. Can confirm at least for me that this was not the root issue, yuidocs was just messing with the logs...
