### ISSUE TITLE
Attempting to render svg elements with Glimmer2 fails

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#286]
Stacktrace: https://gist.github.com/bcardarella/87be33c174e11ae2cdb643f7feff4de1

It looks like Glimmer expects `NS` functions, which SimpleDOM doesn't yet support.

**Comment by rwjblue** [comment]
I created https://github.com/ember-fastboot/simple-dom/issues/23 to track the issue upstream in simple-dom.

**Comment by rwjblue** [comment]
I created a reproduction here: [rwjblue/fastboot-svg-test](https://github.com/rwjblue/fastboot-svg-test).

Basic steps:

1) `ember new fastboot-svg-test`
2) `cd fastboot-svg-test`
3) Ensure using Ember 2.10.0-beta.1 or higher
4) Create a template at `app/templates/application.hbs` with the following:

```hbs
<svg  xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink">
    <rect x="10" y="10" height="100" width="100"
          style="stroke:#ff0000; fill: #0000ff"/>
</svg>
```

5) Install Fastboot `ember install ember-cli-fastboot`
6) Run `ember fastboot`
7) Open browser to `http://localhost:3000`
8) See error in console.

**Comment by rwjblue** [comment]
Had a long conversation with @krisselden about this in Slack, and I think we have a path forward here. I'll shoot for getting Glimmer updated tomorrow, but it somewhat depends on just how much work there is...
