### ISSUE TITLE
Better logging when falling back to resilient mode in `ember fastboot`

### ISSUE THREAD

**Issue by Redsandro** [ember-fastboot/ember-cli-fastboot#290]
Hi, I'm new to fastboot. I've been watching the project for a while in anticipation and decided it's time to give it a go.

I can't seem to get pre-rendered html. I'm sorry if I missed a step or didn't read correctly

Serving with `ember fastboot -prod --serve-assets` and running `curl http://localhost:3000` I get this body:

```
	<body class="homepage">

		<!---->

		<script src="assets/vendor-426f65f2a272d0029cf05f86b91d0b4c.js" integrity="sha256-kOx5HB/SuiOldgU+PDpMEvE6JTV2muHJ0gYiKr0xxyM= sha512-QE9Gl6moFBOr2WoSkp5ZtQdN2SZZsSAiRsi3JK6IMRRtpY+zGtvXauU7gujBIJrej0Hgr4scjcYSp+lSgV/Kbg==" ></script>
		<script src="assets/winmix-8e3f124ca4d9253d06de7f79ffcc5df6.js" integrity="sha256-YqllFDLdaP7G7RBKJ6okV1F3emFDWJnqGCMii5l6xL0= sha512-nu7pXEshAvVeg3uG7cRoUQm2QUwtaQWbSKAEI56H5MnzRp6HLEvvKCRm+zHCWZkEC5zuCgWzjDpxkNfnyD3AFA==" ></script>
		
	</body>
```

This is similar-ish to not using fastboot.

```
DEBUG: Ember      : 2.7.0
DEBUG: Ember Data : 2.7.0
```

```
ember-cli-fastboot@1.0.0-beta.13
```

**Comment by Redsandro** [comment]
Disregard that - I fixed all the errors that caused the page not to show or to only show an error message on the page. I thought any errors left showing on the console were non-crucial.

:bulb: *Idea:* Show a message on the console: _"Falling back to non-fastboot pageview"_

**Comment by rwjblue** [comment]
Interesting. Yes, I think we can and should do something like this. Even though the error is in the terminal console it isn't completely obvious when you look in the browser.

**Comment by Redsandro** [comment]
I might be wrong because my code sandbox is a bit messy, but when falling back to non-fastboot mode, it seems that `fastboot.isFastBoot` is still true.

This is unwanted, for example when using `fastboot.isFastboot` for switching between using headers from the `fastboot` service and using `window.navigator`.

**Comment by kratiahuja** [comment]
Given `ember fastboot` is now deprecated over `ember s`, this issue/feature is more better suited for `fastboot-express-middleware` repo.
