### ISSUE TITLE
CSS hot reloading not working

### ISSUE THREAD

**Issue by mike183** [ember-fastboot/ember-cli-fastboot#293]
This appears to be a repeat of #212 and #226, the issue was previously resolved but seems to have resurfaced.

After some digging, it looks like that the regression was introduced in v1.0.0-beta.11, more specifically #282.

**Comment by lolmaus** [comment]
Clarification: in my case, CSS hot reloading does work, but it is immediately followed by full tab refresh, defeating the purpose.

@mike183 Thank you for the heads-up. :bow:

**Comment by jakeleboeuf** [comment]
For me, a combination of this `ember-network` [PR](https://github.com/tomdale/ember-network/pull/12) which was merged and released in v0.3.1 and [this commit](https://github.com/ember-fastboot/ember-cli-fastboot/commit/99e94339899777ccfee80eea2389b8a449cfff5e) fix the issue.

**Comment by gandalfar** [comment]
This also breaks live reloading with `ember serve`.

**Comment by gandalfar** [comment]
Full reload happens because `ember-cli:live-reload: files %a +1ms [ 'assets/frontend.css', 'package.json' ]` gets `package.json` as changed file and triggers a full page reload.

**Comment by vlascik** [comment]
@gandalfar is there any fix for this?

**Comment by gandalfar** [comment]
As a workaround, you could try: `FASTBOOT_DISABLED=true ember serve`. Since editing (S)CSS is something you don't often need fastboot enabled.

**Comment by stefanpenner** [comment]
may be fixed by https://github.com/ember-fastboot/ember-cli-fastboot/pull/369 cc @kratiahuja

**Comment by kratiahuja** [comment]
Yup this should be fixed with the unified serve.
