### ISSUE TITLE
Problem with https redirect on production (with nginx proxy) 

### ISSUE THREAD

**Issue by max-konin** [ember-fastboot/ember-cli-fastboot#296]
Hi 

I have fastboot server and Nginx proxy. The application works over https (Nginx receive https requests but works with fastboot over http) 

When I go to https://my-app.com I should be redirected to https://my-app.com/en. But fastboot puts to 'location' header url with http protocol instead of https.

I think the reason is this: 
https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/app/locations/none.js#L37

Maybe It should be placed to config

**Comment by buschtoens** [comment]
Can you share your nginx config? The `Location` header can be rewritten by nginx to avoid this: [`proxy_redirect`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect)

**Comment by max-konin** [comment]
```
location @fastboot {
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header Host $http_host;
  proxy_redirect off;
  proxy_pass http://fastboot;
}
```

For redirect from http to https I use rewrite. But when I request / I have 2 redirect:
http://../ -> http://../en
http://../en -> https://../en

**Comment by buschtoens** [comment]
`proxy_redirect off;` <-- There's your problem.

Give this a try: `proxy_redirect http:// https://;`

I assume you defined `fastboot` as an `upstream` block?

**Comment by max-konin** [comment]
Thanks. I'll try use proxy_redirect.

But I thought that It can be resolved on fastboot's side (like in Rails)

**Comment by buschtoens** [comment]
Personally I wouldn't do that. Your reverse proxy speaks in HTTP to the fastboot server, so fastboot should respond accordingly. But that's just my opinion.

Feel free to reopen this issue, if my solution doesn't work or you need further configuration options.
