### ISSUE TITLE
modelClass argument for Serializer.normalizeResponse is string in Fastboot env

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#297]
In Fastboot env the `modelClass` argument for Ember Data serializer's `normalizeResponse` function is coming in as a string not a modelClass type.

Based upon our non-Fastboot env this argument should be a model class.

tbh I'm not sure what the expected API is here. I've tried to trace the stack in Fastboot to see why this is happening but didn't have much success.

**Comment by danmcclain** [comment]
The patching of Ember Data is limited to this file, and only touches `adapter._ajaxRequest`. Do you happen to be using ember-data-fastboot?

**Comment by bcardarella** [comment]
yup, we're using that addon

**Comment by danmcclain** [comment]
I would investigate there, I think that it has a custom serializer

**Comment by danmcclain** [comment]
I may be wrong on the serializer, I thought it did

**Comment by bcardarella** [comment]
It doesn't, it is only an initializer to dump into the shoebox. This error is happening before that.

**Comment by bcardarella** [comment]
But that did give a clue as to the problem and I believe I found it, related to our app and not fastboot. Thanks.
