### ISSUE TITLE
charset=utf-8 set on every non GET request

### ISSUE THREAD

**Issue by juanazam** [ember-fastboot/ember-cli-fastboot#298]
Hi,

When my app runs in fastboot mode, I see every non GET request been sent to the my JSON API server includes the `charset` parameter which is not allowed as described on JSON API's spec: http://jsonapi.org/format/#content-negotiation-servers.

This is happening because of najax, so I created an issue on the najax repository: https://github.com/najaxjs/najax/issues/49.

**Comment by danmcclain** [comment]
@juanazam did we cut a new release of with the right version of najax (not sure which version https://github.com/najaxjs/najax/pull/55 made it into)

**Comment by kratiahuja** [comment]
Is this still an issue?

**Comment by juanazam** [comment]
@danmcclain @kratiahuja the fix was introduced on najax v1.0.1 and it seems we are using v1.03 https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/yarn.lock#L4440.

We should be on the safe side now.

Closing.
