### ISSUE TITLE
Discrepancy between window's and FastBoot's reported protocol

### ISSUE THREAD

**Issue by martletandco** [ember-fastboot/ember-cli-fastboot#304]
`window.location.protocol` includes the colon (`https:`) whereas `request.protocol` does not (`https`). As this adds an additional step in getting a consistent protocol value it, introduces a 'gotcha'.

```
let location = get(this, 'fastboot.isFastBoot') ? get(this, 'fastboot.request') : window.location;
let protocol = get(location, 'protocol');
```
becomes

```
let location = get(this, 'fastboot.isFastBoot') ? get(this, 'fastboot.request') : window.location;
let protocol = get(location, 'protocol');
protocol = protocol.replace(':', '');
```

Which doesn't seem right to me but I'm not sure if I'm missing something and FastBoot's request object is aligning with a different interface.

Happy to make a PR if this is a bug rather than my misunderstanding.

**Comment by danmcclain** [comment]
This is an oversight rather than intentional (and caused by express not returning the colon), the file to update is here in `ember-fastboot/fastboot` https://github.com/ember-fastboot/fastboot/blob/9899016ca5f23748e6650d88fdb2a2b52d7a0e71/src/fastboot-request.js#L7

If you want to PR, that would be awesome, if not, mind closing and opening this issue on `fastboot` itself?

Thanks!

**Comment by martletandco** [comment]
Thanks for letting me know, I'll close this issue and open a PR on `ember-fastboot/fastboot`. Will be later on as my internet is patchy ATM but will post the link here.

Does `ember-fastboot/ember-cli-fastboot` need a PR for a dependency update? I can't determine the exact relationship between the two.

**Comment by DrewCarlson** [comment]
@martletandco ember-cli-fastboot depends on [fastboot-express-middleware](https://github.com/ember-fastboot/fastboot-express-middleware) which depends on fastboot.

**Comment by martletandco** [comment]
PR is here: https://github.com/ember-fastboot/fastboot/pull/119
