### ISSUE TITLE
JSHint isn't running on /app folder in CI

### ISSUE THREAD

**Issue by kellyselden** [ember-fastboot/ember-cli-fastboot#307]
I can't think of a reason why.

**Comment by rwjblue** [comment]
`app/` in addons is never linted 😢 

There should be an issue in ember-cli for it I think...

**Comment by kellyselden** [comment]
Wow I can't believe I didn't know this until now...

**Comment by rwjblue** [comment]
Well, we should totally fix it. It makes me sad that I haven't yet. :(
