### ISSUE TITLE
How to access FastBoot global env

### ISSUE THREAD

**Issue by Blackening999** [ember-fastboot/ember-cli-fastboot#324]
Having issues accessing FastBoot in a global mode. For instance in a component.

```js
if (typeof FastBoot !== 'undefined') {
  const modddddule = FastBoot.require('SOME-NPM-MODULE')
}
```

I'm simply receiving FastBoot to be undefined. I'm running it under
```
ember fastboot --serve-assets
```
so it should be in FastBoot mode :)

**Comment by vkoves** [comment]
I'm not sure what your precise configuration is, but in our project we don't reference FastBoot like that precisely. Rather we do `this.get('fastboot')`, which fetches Fastboot out of the current context. We also do `		fastboot: _ember['default'].inject.service()` to make this accessible, as in EmberJS I don't believe globals really function like that.

**Comment by andrewfan** [comment]
@Blackening999 i think in components you should use `fastboot` service

**Comment by kratiahuja** [comment]
Going to close this.
