### ISSUE TITLE
Set a lang attribute in html tag

### ISSUE THREAD

**Issue by pohodnya** [ember-fastboot/ember-cli-fastboot#331]
How can i set a lang attribute in html tag for fastboot-rendered page?

Now I do it in root route:
```coffee
afterModel: (locale) ->
  unless @get('fastboot.isFastBoot')
    document.getElementsByTagName("html")[0].setAttribute("lang", locale.get('name'))

**Comment by jasonmit** [comment]
Related to https://github.com/ember-fastboot/fastboot/issues/101

**Comment by eshtadc** [comment]
I don't see a way that this is possible in the way fastboot renders the html.  Linked an issue in the fastboot repo to this one.

**Comment by SergeAstapov** [comment]
SimpleDOM has a `documentElement` reference https://github.com/ember-fastboot/simple-dom/blob/master/src/simple-dom/document.ts

Seems this can be handled in a similar way as https://github.com/ember-fastboot/fastboot/pull/171

It can be accessed as
```
getOwner(this).lookup('service:-document').documentElement.setAttribute('lang', 'es')
```

and then it needs to be handled in `insertIntoIndexHTML` function in `src/result.js` similar to how bodyAttributes  assigned to `<body>`.

Does it make sense? I'm missing anything?

**Comment by rwjblue** [comment]
Nope, seems good.
