### ISSUE TITLE
Can we move the service to addon/ ?

### ISSUE THREAD

**Issue by demersus** [ember-fastboot/ember-cli-fastboot#332]
Other addons keep there files in addon/  and import them from their app/ folder to make it easy to do the same in the actual app.  For example, simple-auth makes it easy to make your own session service and import their session service to extend it.

I would like to add some custom functionality to the fastboot service within my app, and i'm not sure how to import and extend it with this current folder structure.

Thank you!

**Comment by rwjblue** [comment]
Yep, absolutely! We should move all of the actual implementation code in `app/` into `addon/` and reexport (as you mentioned).

Would love a PR doing that...

**Comment by demersus** [comment]
:+1:

**Comment by demersus** [comment]
https://github.com/ember-fastboot/ember-cli-fastboot/pull/335

**Comment by locks** [comment]
`/app` currently only reexports. Thanks for your initial work!
