### ISSUE TITLE
Testing story

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#333]
One thing that is lacking right now is how do we properly test Fastboot builds. Because the build can comprise of so much environment specific branched code there are paths that will never be hit in the regular Ember testing environment currently. This becomes exacerbated when libraries like https://github.com/ronco/fastboot-filter-initializers are brought in. Now we have entire modules that aren't even in the test build anymore.

I believe strongly that testing fastboot builds should be part of the 1.0 roadmap and I don't see anything about it in #98. I'm happy to contribute our experience with this so far to provide use cases.

**Comment by danmcclain** [comment]
Existing issue and effort: https://github.com/ember-fastboot/ember-cli-fastboot/issues/111

**Comment by bcardarella** [comment]
Ah, thank you. Totally missed that.
