### ISSUE TITLE
Issue with error states and ember-data

### ISSUE THREAD

**Issue by The-Don-Himself** [ember-fastboot/ember-cli-fastboot#347]
I've realized that ember error state pages don't load in fastboot. I'm specifically talking about when ember-data return a 4xx or 5xx error. In this case, fastboot response status is a 500 error code with a not so pretty message to match. Without fastboot error pages load properly.

**Comment by kratiahuja** [comment]
Do you have the error hook defined in your app? If so the ember data error should bubble up to the error hook and you can transition to the error page which would not cause the fastboot to return 4xx or 5xx.

**Comment by The-Don-Himself** [comment]
@kratiahuja Thanks for looking into this, it's been a few months but I believe the issue is still active.  I also believe I have the error hooks all set up correctly because as stated the correct error pages show without Fastboot for example, if you were to click on a click post-Fastboot which results in a 4xx or 5xx, you'll get the correct application error pages response but going to it directly results in a 500.

I have been using a workaround I came up with by manipulating the responses from fastboot-app-server by explicating creating a server-error route and piping responses to it as below.

````
const request = require('request');
const FastBootAppServer = require('fastboot-app-server');

// Custom Middlewares
function modifyRequest(req, res, next) {
    next();
};
function handleErrors(err, req, res, next) {
    let statusCode = err.errors[0].status;
    if(statusCode == 404){
        request('http://127.0.0.1/page-not-found').pipe(res);
    } else if (statusCode == 503) {
        request('http://127.0.0.1/server-error').pipe(res);
    } else {
        next();
    }
};

let server = new FastBootAppServer({
    distPath: 'C:\\wamp64\\www\\campus-discounts\\dist',
//    gzip: true,
    beforeMiddleware: function (app) { app.use(modifyRequest); },
    afterMiddleware: function (app) { app.use(handleErrors); }
});

server.start();
````

When I created this issue, I look around for some other ember web apps that use Fastboot and I noted that it seems I was not the only one affected.

For example, I found this awesome site called [Ludo](https://www.ludu.co/) which uses Fastboot. @t4t5 seems to be the developer behind it (I hope you don't mind me mentioning you and your app!) They provide educational material, if you visit a course say https://www.ludu.co/course/ember, things are ok, but if you visit a not-found course say https://www.ludu.co/course/ember2.13 it results in a 500 error page. This was the same behaviour I was getting. Perhaps @t4t5 can confirm if this is an issue he faces.

It been a while and I can try retest but I think the issue is still valid. My workaround results in a somewhat more expected behaviour eg https://campus-discounts.com/discounts/55555555

**Comment by Serabe** [comment]
@The-Don-Himself I cannot reproduce this with fastboot 1.0.5, and ember 2.15.0. Is this still an issue for you?

**Comment by The-Don-Himself** [comment]
@Serabe I'm still in the process of upgrading to fastboot stable from beta-19 because of all the incompatible browser plugins I use during app.import in ember-cli-build.js, as such I haven't tested in the later versions of fastboot. 

I guess I'll just close it for now, until I can reproduce after upgrade.
