### ISSUE TITLE
disable fastboot with unified serving

### ISSUE THREAD

**Issue by mfazekas** [ember-fastboot/ember-cli-fastboot#358]
#356 unifies fastboot serving. Apps having `ember-cli-fastboot` in their `package.json` will get fastboot render with ember 2.12 or later when pointing browser to `http://locahost:4200`.

It would be great to provide some options to get non fastboot render. 

Usecases:
- i see some issue in fastboot version and want to check if i see the same on regular version
- i've started fastboot adoption, but it's work in progress so i still want to default to non fastboot version for any feature work
- browser vs node.js dev experience - debugging

Current options, and it's limitations:
- remove `ember-cli-fastboot` from package.json. 
    Issues:
    - requires restart
    - if code uses `service:fastboot` we get `Attempting to inject an unknown injection: 'service:fastboot'`
- set `FASTBOOT_DISABLED`=TRUE
    Issues:
    - requires restart
    - currently it's half baked as does disable package.json generation, but doesn't disable fastboot serving, which results in `Couldn't find package.json error from EmberApp.readPackageJSON`

See:
https://github.com/ember-fastboot/ember-cli-fastboot/pull/356#issuecomment-281784396

**Comment by mfazekas** [comment]
I think the best would be if apps could have to option to default to non fastboot version in general, and we would have the option to get the fastboot version via query parameter for example

**Comment by stefanpenner** [comment]
What if there was a `?_fastboot=true|false` optional query param. That way you could toggle on a per request basis (to aide in quick debugging)

**Comment by kratiahuja** [comment]
In the fastboot meeting yesterday we decided to explore either the query param option as @stefanpenner suggested or have an process environment variable. I will address this once that PR is merged.

**Comment by fotinakis** [comment]
@kratiahuja +1 for environment variable, especially so there's no chance of a malicious user disabling fastboot in a prod app.

**Comment by rwjblue** [comment]
FWIW, what we do here is generally unrelated to how it will work in production. The `ember serve` server is not intended for production use (you'd generally use `fastboot-app-server` or similar system that leverages the `fastboot-express-middleware` independently).

**Comment by fotinakis** [comment]
Great, that's good to know, I haven't actually run fastboot in production yet.

**Comment by stefanpenner** [comment]
> @stefanpenner suggested or have an process environment variable.

@kratiahuja seems like we should do both.

**Comment by kratiahuja** [comment]
@stefanpenner +1 to both

**Comment by josemarluedke** [comment]
I do think having both options is appropriate. Having environment variable to entirely disable FastBoot would allow people to move their application to FastBoot in steps. We had FastBoot in our application for a month and it was disabled until we were comfortable pushing to production. Also, allowing to disable FastBoot in a specific page in runtime would allow developers to debug errors easier without needing to set environment variable and restart the application.

**Comment by danmcclain** [comment]
@josemarluedke this option would only apply when calling `ember serve` in development (both options that is). Running in development via ember serve is separate from running in production via fastboot-app-server. (This also echoes what @rwjblue said)

**Comment by josemarluedke** [comment]
@danmcclain Yes, I was expecting to only be an development option. Production environment should be up to the developer to configure fastboot-app-server as they wish.

**Comment by kratiahuja** [comment]
I will address this once #356 lands.
