### ISSUE TITLE
Potentially bug in simple-dom serialization

### ISSUE THREAD

**Issue by Padchi** [ember-fastboot/ember-cli-fastboot#361]
My server returns a sorted list based on a property that contains the Swedish characters `Å, Ä, Ö`.
These three are the last three in the Swedish alphabet but for some reason FastBoot reads them as  "slugs" (å -> a, ä -> a, ö -> o) and the sort order becomes wrong. If I sort the list in ember it's the same thing on the initial render with FastBoot except that the order changes when the javascript kicks in to the correct one and the user can see when the list changes sort order.

For example, this sorted response from server:
```
1. Pxx
2. Åxx
3. Äxx
4. Öxx
```
becomes:
```
2. Åxx
3. Äxx
4. Öxx 
1. Pxx
```
when fastboot renders list and when my app takes over, it changes to:
```
1. Pxx
2. Åxx
3. Äxx
4. Öxx
```

**Comment by krisselden** [comment]
Ember uses String.prototype.localeCompare which in the browser uses the users locale but in node it depends on the node version and how v8 was built and then it would be the servers locale. I'm not sure if you can set the locale for the sandbox

**Comment by krisselden** [comment]
But this is not a simple dom issue

**Comment by Padchi** [comment]
So @krisselden, how can I fix this then? I've try to set the right locale on ubuntu but that's seems not to work.

**Comment by krisselden** [comment]
@Padchi I think this is more of a node issue, you should search for how to set the default locale for localeCompare.

On node 6.9.2
```
> ['Pxx', 'Åxx', 'Äxx', 'Öxx'].sort()
[ 'Pxx', 'Äxx', 'Åxx', 'Öxx' ]
> ['Pxx', 'Åxx', 'Äxx', 'Öxx'].sort((a, b) => a.localeCompare(b))
[ 'Åxx', 'Äxx', 'Öxx', 'Pxx' ]
> ['Pxx', 'Åxx', 'Äxx', 'Öxx'].sort((a, b) => a.localeCompare(b, 'sv'))
[ 'Åxx', 'Äxx', 'Öxx', 'Pxx' ]
```

Ember by default uses that middle version.  You can use a custom sort to do the third.  I think older versions of node had a broken localeCompare, are you on the LTS?

**Comment by hjdivad** [comment]
@Padchi as @krisselden mentioned this is really a node issue.  From what I can tell your options are

1. Do a custom sort (in which case you can rely on just `sort` rather than `localeCompare`) or
2. Build a node with ICU support.  See the [Intl guide](https://github.com/nodejs/node/wiki/Intl)

The test you can run to ensure things are working is when you can run
```js
> ['Pxx', 'Åxx', 'Äxx', 'Öxx'].sort((a, b) => a.localeCompare(b, 'sv'))
```

and get

```js
// => [ 'Pxx', 'Äxx', 'Åxx', 'Öxx' ] 
```

**Comment by hjdivad** [comment]
tyvärr :(

**Comment by Padchi** [comment]
Ended up with my own sort function. Feels weird tho that fastboot ignores the sorted data from the server and sorts it by its own.

Skickat från min iPhone

**Comment by tomdale** [comment]
@Padchi Hmm, so are you saying that the list is being sorted on the server, and then it is being re-sorted (incorrectly) in the Ember app running in FastBoot? Are you not expecting that it gets re-sorted? Would you mind sharing how you are fetching the data from the server?

**Comment by Padchi** [comment]
@tomdale never mind, wrong by me. Fastboot was respecting my sorted data. I will close this for now as it seems like it's a  node problem and has nothing tot do with fastboot.

**Comment by tomdale** [comment]
@Padchi Excellent news. Please let us know if there is anything we can do to make the locale handling more correct by default. It seems like a tricky problem I don't have a lot of experience with. If there's a way to infer the correct locale we should consider whether we can do it automatically, assuming it's fast and reliable.
