### ISSUE TITLE
Debugging Fastboot with VS Code

### ISSUE THREAD

**Issue by taras** [ember-fastboot/ember-cli-fastboot#366]
VS Code has a very good Node debugger. I've tried using it to debug a Fastboot app and I haven't been able to get it to work.

Is it possible? Do you have it working? How do you do it?

**Comment by kratiahuja** [comment]
@taras did you see the node debugger instructions here: https://github.com/ember-fastboot/ember-cli-fastboot#developer-tools ?

**Comment by taras** [comment]
@kratiahuja yes, but that it doesn't talk about Visual Studio Code. I was hoping to see if someone figured out how to use Visual Studio Code.

**Comment by kratiahuja** [comment]
@taras I am not sure what is not working for you. Happy to look into it if you could mention in detail how you are using it and what doesn't work.

**Comment by andrewfan** [comment]
@taras @kratiahuja hey, this is my config for none fastboot apps
```
{
      "name": "Launch Ember CLI",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/ember-cli/bin/ember",
      "args": [
        "server"
      ]
    },
```
it also launches fastboot apps but for some reasons FastBoot global variable is not defined during the debug

**Comment by jasonmit** [comment]
For those on node 8, you can `--inspect{-brk}` along with Chrome's inspector `chrome://inspect`:
`node --inspect-brk ./node_modules/.bin/ember s`

**Comment by taras** [comment]
@kratiahuja sorry, I missed this. This was a while ago. It looks like a few people shared some solutions. We can close this issue. Thank you
