### ISSUE TITLE
API call data removed if I used ember fastboot --serve-assets

### ISSUE THREAD

**Issue by ivanhueso** [ember-fastboot/ember-cli-fastboot#372]
For some reason only when I'm serving with assets such as `--serve-assets`  any API requests I make are been called twice. One on the server, one on the client side.

To prevent this I make my calls inside `  if(this.get('fastboot.isFastBoot')){ .... }` 
and it loads only on the server as it should and want it. However the problem comes right on when after some second of been loaded the data wipes outs.  If I don't use serve-assets it just work fine.

I can't find a solution for this.

**Comment by kratiahuja** [comment]
@ivanhueso have you looked at the [shoebox API](https://github.com/ember-fastboot/ember-cli-fastboot#the-shoebox) ? That basically will use the API data that was used requested on behalf of server side rendering on client.

**Comment by simonihmig** [comment]
> For some reason only when I'm serving with assets such as --serve-assets any API requests I make are been called twice. One on the server, one on the client side.

That is what I would have expected. The ember app running in the browser does not know about the previous API requests and has to rerun them. When not using `--serve-assets` the ember app does not run on the client at all I guess, explaining why no API requests are made. 

As suggested by @kratiahuja the shoebox is the way to "reuse" API requests on the client. If you happen to use ember-data and JSON:API, you can use https://github.com/cardstack/ember-data-fastboot, which should work out of the box.

**Comment by ivanhueso** [comment]
I've used the shoebox API and it works as expected. Thank you @kratiahuja  & @simonihmig
