### ISSUE TITLE
transitionTo under https

### ISSUE THREAD

**Issue by zion03** [ember-fastboot/ember-cli-fastboot#379]
@zion03 commented on [Fri Apr 21 2017](https://github.com/ember-fastboot/fastboot/issues/135)

I'm trying to transition `fastboot` under the `https`, it's works with redirection to `http` version.

For example `application.js` route

```
export default Ember.Route.extend({
  model: function(param){
    this.transitionTo('login');
  }
});
```
request: `https://domain.com` -->  `http://domain.com:3001/login`
where `3001` fastboot port

How I can solve this problem?

**Comment by danmcclain** [comment]
Do you have a proxy like nginx in front of FastBoot? I'm assuming so since you are using SSL. Make sure that you forward your headers, as FastBoot is receiving an http request from your proxy and doesn't know that it's actually an https request from the browser. I think you need to pass X-forwarded-proto like in this article https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

**Comment by zion03** [comment]
More details about our production environment:

We are using Amazon ELB, and we use https listener on a custom port, f.e. 44443 and we terminate SSL on this loadbalancer. We send a request to https://example.com:44443, per Amazon documentation, ELB sets X-forwarded-proto to the same schema as original request has. https in this case case. ELB accesses fastboot via http

Actually we use nginx also, but it sits before ELB described above, and proxy_pass requests using https to this ELB.
We see the same redirect behavior in both cases even we request directly via ELB https://example.com:44443 or using via nginx proxy_pass

**Comment by kratiahuja** [comment]
You should be able to use a middleware that redirects to https. See here: https://github.com/ember-fastboot/fastboot-app-server/issues/36

**Comment by kratiahuja** [comment]
Going to close this as you can redirect via a middleware. Please feel free to reopen if this doesn't work for you.

**Comment by devdemi** [comment]
@kratiahuja I have the same problem as @zion03 but middleware doesn't help me. 
My fastboot works behind nginx on port 3443 and when any `transitionTo` called fastboot will transfer to domain.com:3443 

Lines from my nginx config:
```
    location / {
        if ($http_x_forwarded_proto != 'https') {
            return 301 https://$host$request_uri;
        }
        #try_files @fastboot $uri $uri/ /index.html;
        resolver 8.8.8.8;
        proxy_pass https://$server_name:3443;
        proxy_redirect     off;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;
    }
```
But any additional header can't make fastboot doesn't add the port to a hostname.
