### ISSUE TITLE
[bug?] headers as strings on handleResponse on fastboot mode

### ISSUE THREAD

**Issue by marcemira** [ember-fastboot/ember-cli-fastboot#381]
Hello, today I struggled big time until I realized that my adapter's `handleResponse` function had headers parameter as a string inside an property `server` inside it, instead of the regular object from ED. So In order to fix that I did the following:
```javascript
handleResponse(status, headers, payload, requestData) {
    let _headers = headers;
    if(typeof FastBoot !== 'undefined'){
      let merged = {};
      headers.server.split('\n').map((l) => {
        let line = l.split(': ');
        let o = {};
        line[0] = line[0].split('-').map((k) => k.charAt(0).toUpperCase() + k.substr(1,k.length-1)).join('-');
        o[line[0]] = line[1];
        return o;
      }).forEach((o) => Object.assign(merged, o));
     _headers = merged;
    }
   ...
```

**Comment by kratiahuja** [comment]
Can you provide a reproduction for us to investigate?

**Comment by marcemira** [comment]
@kratiahuja I'm afraid I won't have the time to provide one, but it should be a matter of checking the `headers` param of that function on a adapter, while the code runs on fastboot. It returns the response's header as a string, instead of an Object (while on runtime). My apologizes for not been able to follow it right now.

**Comment by kratiahuja** [comment]
I have not heard anyone else hitting this issue nor do I understand when this happening. If you can provide some steps to reproduce, it would be great.

**Comment by marcemira** [comment]
@kratiahuja Let's close it for now. Unfortunately I don't have the time to reproduce it right now. I stumbled upon it and posted a solution so anyone else hitting the same issue could find a workaround it until it gets solved.

**Comment by kratiahuja** [comment]
Sounds good. Feel free to reopen if you have a reproduction. Happy to take a look.
