### ISSUE TITLE
`ember fastboot` does not terminate with ember-cli >= 2.13

### ISSUE THREAD

**Issue by simonihmig** [ember-fastboot/ember-cli-fastboot#386]
Reproduction:

```bash
ember new app
cd app
ember install ember-cli-fastboot
ember fastboot
// press ctrl-c
```

This shows `cleaning up...` but the process never terminates. Just sending a `SIGKILL` will terminate it. No problems like that with `ember serve`, or when downgrading to ember-cli 2.12.

Don't know if it's worth fixing, as `ember fastboot` is deprecated anyways, but it broke some test setups, see https://github.com/tomdale/ember-cli-addon-tests/issues/96

**Comment by stefanpenner** [comment]
I suspect this isn't an issue \w #369, can you confirm?

**Comment by kratiahuja** [comment]
With #369 `ember fastboot` will be killed :)

**Comment by simonihmig** [comment]
@stefanpenner I quickly tested this with the #369 branch, and the issue does still exist, when running with the (already now) *deprecated* `ember fastboot` command. With `ember s` this is not an issue, neither with the current release nor with #369.

@kratiahuja `ember fastboot` is still there in your PR. Is it supposed to be removed with the next release?

**Comment by stefanpenner** [comment]
> @kratiahuja ember fastboot is still there in your PR. Is it supposed to be removed with the next release?

We should likely leave it for the first release but deprecate it, then remove it shortly thereafter.

@simonihmig I think ^ is a WONTFIX, as `ember s` will replace it (and it works correctly).

**Comment by simonihmig** [comment]
@stefanpenner As I said in the beginning, I am ok with not fixing this when this is too much effort. But I would then probably kill this asap...

Was more an issue with some test setups still running the old command, which I fixed today (https://github.com/tomdale/ember-cli-addon-tests/pull/98, https://github.com/kaliber5/ember-fastboot-addon-tests/pull/11, https://github.com/kaliber5/ember-fastboot-app-tests/pull/1)

**Comment by kratiahuja** [comment]
> We should likely leave it for the first release but deprecate it, then remove it shortly thereafter.
@simonihmig I think ^ is a WONTFIX, as ember s will replace it (and it works correctly).

The deprecation message already exists today. See [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/lib/commands/fastboot.js#L87) . I am totally fine with leaving it for few more releases too.

**Comment by kratiahuja** [comment]
> @kratiahuja ember fastboot is still there in your PR. Is it supposed to be removed with the next release?

I wanted to kill things in a subsquent PR since that PR has got really long to review for anyone.

**Comment by ro0gr** [comment]
@stefanpenner fyi https://github.com/ember-cli/ember-cli/pull/7019 fixes this issue.

**Comment by simonihmig** [comment]
Closing this as the root issue seems to be in ember-cli as reported. @ro0gr thanks for investigating this!
