### ISSUE TITLE
Add-ons Prep for fastboot 1.0.0

### ISSUE THREAD

**Issue by stefanpenner** [ember-fastboot/ember-cli-fastboot#387]
## Pre-req

- [x] release fastboot 1.0.0.rc1

## What/Why?

The upcoming ember-cli-fastboot 1.0.0 release has some breaking changes, although we try hard to avoid any breaking changes these ones are hard to avoid (and we feel worth it) they:

* dramatically improve build performance
* unify `ember fastboot --serve` and `ember s`
* put us on a path of success

## How to upgrade:

@kratiahuja's upgrade guide: https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c

* if you are upgrading or have submitting a pull request, please leave a comment in this issue and we will update the add-on list (and then remove your comment)

## Addons

List of add-ons that match: https://emberobserver.com/code-search?codeQuery=process.env.EMBER_CLI_FASTBOOT

To check them off they should be either ready for 1.0.0, and add a link to any active PR that enables 1.0.0

- [ ] [PR](https://github.com/mike-north/ember-calendly/pull/77) ember-calendly [homepage](https://github.com/mike-north/ember-calendly#readme)
- [ ] [PR](https://github.com/mike-north/ember-add-to-homescreen/pull/79) ember-add-to-homescreen [homepage](https://github.com/mike-north/ember-add-to-homescreen#readme)
- [x] [PR](https://github.com/PrinceCornNM/ember-algolia/pull/2) ember-algolia [homepage](https://github.com/PrinceCornNM/ember-algolia#readme)
- [x] [PR](https://github.com/aupac/ember-aupac-typeahead/pull/53) ember-aupac-typeahead [homepage](https://github.com/aupac/ember-aupac-typeahead)
- [x] [PR](https://github.com/this-dot/ember-background-video/pull/1/files) ember-background-video [homepage](https://github.com/this-dot/ember-background-video#readme)
- [ ] [PR](https://github.com/davewasmer/ember-baremetrics-calendar/pull/10/files) ember-baremetrics-calendar [homepage](https://github.com/davewasmer/ember-baremetrics-calendar#readme)
- [x] [PR](https://github.com/topaxi/ember-bootstrap-datepicker/pull/1) ember-bootstrap-datepicker [homepage](https://github.com/topaxi/ember-bootstrap-datepicker#readme)
- [ ] [PR](https://github.com/mike-north/ember-c3-shim/pull/91) ember-c3-shim [homepage](https://github.com/mike-north/ember-c3-shim#readme)
- [x] [PR](https://github.com/kinesisptyltd/ember-chroma-shim/pull/29)ember-chroma-shim [homepage](https://github.com/Soliah/ember-chroma-shim#readme)
- [ ] [PR](https://github.com/jakeleboeuf/ember-cli-bodymovin/pull/1) ember-cli-bodymovin [homepage](https://github.com/jakeleboeuf/ember-cli-bodymovin#readme)
- [ ] ember-cli-bootstrap-4 [homepage](https://github.com/kaermorchen/ember-cli-bootstrap-4)
- [ ] ember-cli-bootstrap-bookingsync-sass [homepage](https://github.com/BookingSync/bootstrap-bookingsync-sass#readme)
- [ ] [PR](https://github.com/soulim/ember-cli-bootstrap-datepicker/pull/100) ember-cli-bootstrap-datepicker [homepage](https://github.com/soulim/ember-cli-bootstrap-datepicker#readme)
- [x] [PR](https://github.com/lifegadget/ember-cli-bootstrap-sassy/pull/49) ember-cli-bootstrap-sassy [homepage](https://github.com/lifegadget/ember-cli-bootstrap-sassy#readme)
- [x] [PR](https://github.com/binhums/ember-cli-bugsnag/pull/77) ember-cli-bugsnag [homepage](https://github.com/binhums/ember-cli-bugsnag#readme)
- [x] [PR](https://github.com/jkusa/ember-cli-clipboard/pull/27) ember-cli-clipboard [homepage](https://github.com/jkusa/ember-cli-clipboard#readme)
- [x] [PR](https://github.com/josemarluedke/ember-cli-daterangepicker/pull/69) ember-cli-daterangepicker [homepage](https://github.com/josemarluedke/ember-cli-daterangepicker)
- [ ] [PR](https://github.com/FutoRicky/ember-cli-dropzonejs/pull/78) ember-cli-dropzonejs [homepage](https://github.com/FutoRicky/ember-cli-dropzonejs#readme)
- [ ] ember-cli-dropzonejs-secure [homepage](https://github.com/FutoRicky/ember-cli-dropzonejs#readme)
- [ ] ember-cli-fake-server [homepage](https://github.com/201-created/ember-cli-fake-server#readme)
- [ ] ember-cli-fastclick [homepage](null)
- [ ] ember-cli-flexibility [homepage](https://github.com/migeorge/ember-cli-flexibility)
- [ ] ember-cli-foundation-6-sass [homepage](https://github.com/acoustep/ember-cli-foundation-6-sass.git)
- [x] ember-cli-g-maps [homepage](https://github.com/Matt-Jensen/ember-cli-g-maps#readme)
- [x] [PR](https://github.com/ronco/ember-cli-head/pull/21) ember-cli-head [homepage](https://github.com/ronco/ember-cli-head#readme)
- [ ] ember-cli-icheck [homepage](https://github.com/mewben/ember-cli-icheck)
- [ ] ember-cli-image-cropper [homepage](https://github.com/mhretab/ember-cli-image-cropper#readme)
- [ ] ember-cli-jstree [homepage](https://github.com/ritesh83/ember-cli-jstree#readme)
- [ ] ember-cli-maskmoney [homepage](https://github.com/thiagoc7/ember-cli-maskmoney#readme)
- [ ] ember-cli-medium-editor [homepage](https://github.com/lukebrenton/ember-cli-medium-editor#readme)
- [x] [PR](https://github.com/samselikoff/ember-cli-mirage/pull/1098) ember-cli-mirage [homepage](https://github.com/samselikoff/ember-cli-mirage)
- [ ] ember-cli-mirage-nested [homepage](https://github.com/britishgas-engineering/ember-cli-mirage-nested)
- [x] [PR](https://github.com/jasonmit/ember-cli-moment-shim/pull/137/files) ember-cli-moment-shim [homepage](https://github.com/jasonmit/ember-cli-moment-shim)
- [ ] ember-cli-nanoscroll [homepage](https://github.com/Rastopyr/ember-cli-nanoscroller#readme)
- [x] [PR](https://github.com/kellyselden/ember-cli-node-modules-to-vendor/pull/56) ember-cli-node-modules-to-vendor [homepage](https://github.com/kellyselden/ember-cli-node-modules-to-vendor#readme)
- [ ] ember-cli-nouislider [homepage](null)
- [ ] [PR](https://github.com/poetic/ember-cli-photoswipe/pull/39) ember-cli-photoswipe [homepage](https://github.com/poetic/ember-cli-photoswipe#readme)
- [ ] ember-cli-pickadate [homepage](https://github.com/AddJam/ember-cli-pickadate#readme)
- [ ] ember-cli-pouchdb-shim [homepage](null)
- [ ] ember-cli-range-input [homepage](https://github.com/knownasilya/ember-cli-range-input#readme)
- [ ] ember-cli-rollbar [homepage](null)
- [ ] ember-cli-scrollbar [homepage](https://github.com/Keeo/ember-cli-scrollbar#readme)
- [ ] [PR](https://github.com/miguelcobain/ember-cli-selectize/pull/194) ember-cli-selectize [homepage](https://github.com/miguelcobain/ember-cli-selectize#readme)
- [x] ember-cli-showdown [homepage](null)
- [x] [PR](https://github.com/salsify/ember-cli-sticky/pull/20) ember-cli-sticky [homepage](https://github.com/salsify/ember-cli-sticky#readme)
- [ ] ember-cli-stripe-patched [homepage](https://github.com/toosick/ember-cli-stripe-patched)
- [ ] [PR](https://github.com/Suven/ember-cli-swiper/pull/56) ember-cli-swiper [homepage](https://github.com/Suven/ember-cli-swiper#readme)
- [ ] ember-cli-tooltipster [homepage](https://github.com/altrim/ember-cli-tooltipster#readme)
- [ ] ember-cli-trackjs [homepage](https://github.com/jherdman/ember-cli-trackjs#readme)
- [ ] ember-cli-videojs-shim [homepage](https://github.com/joshuairl/ember-cli-videojs-shim#readme)
- [ ] ember-cli-webfontloader [homepage](https://github.com/kuzzmi/ember-cli-webfontloader#readme)
- [x] ember-cognito [homepage](https://github.com/paulcwatts/ember-cognito#readme)
- [ ] ember-colpick [homepage](https://github.com/yapplabs/ember-colpick#readme)
- [ ] ember-dismissible [homepage](https://github.com/spencer516/ember-dismissible#readme)
- [ ] ember-dragula [homepage](https://github.com/kalcifer/ember-dragula#readme)
- [ ] ember-drop [homepage](http://shipshapecode.github.io/ember-drop/)
- [ ] ember-element-resize-detector [homepage](https://github.com/EmberSherpa/ember-element-resize-detector#readme)
- [ ] ember-embark [homepage](https://github.com/mike-north/embark#readme)
- [x] [PR](https://github.com/stefanpenner/ember-fetch/pull/29) ember-fetch [homepage](https://github.com/stefanpenner/ember-fetch#readme) 
- [x] [PR](https://github.com/shipshapecode/ember-flatpickr/pull/182) ember-flatpickr [homepage](https://github.com/shipshapecode/ember-flatpickr#readme)
- [ ] ember-flickity [homepage](https://github.com/travelbank/ember-flickity#readme)
- [ ] ember-fullcalendar [homepage](https://github.com/scoutforpets/ember-fullcalendar#readme)
- [ ] [PR](https://github.com/html-next/ember-gestures/pull/89) ember-gestures [homepage](https://github.com/runspired/ember-gestures)
- [x] ember-gsap [homepage](https://github.com/willviles/ember-gsap#readme)
- [ ] [PR](https://github.com/html-next/ember-hammertime/pull/34) ember-hammertime [homepage](https://github.com/html-next/ember-hammertime#readme)
- [x] [NO-PR provided] ember-headroom [homepage](https://github.com/shipshapecode/ember-headroom#readme)
- [ ] ember-highlight [homepage](https://github.com/knownasilya/ember-highlight#readme)
- [x] ember-indexeddb [homepage](https://github.com/mydea/ember-indexeddb)
- [ ] ember-inert-polyfill [homepage](https://github.com/BrianSipple/ember-inert-polyfill#readme)
- [x] [PR](https://github.com/Exelord/ember-initials/pull/35) ember-initials [homepage](https://github.com/Exelord/ember-initials#readme)
- [x] [PR](https://github.com/pzuraq/ember-inputmask/pull/39) ember-inputmask [homepage](https://github.com/pzuraq/ember-inputmask#readme)
- [x] [PR](https://github.com/PoslinskiNet/ember-introjs/pull/23) ember-introjs [homepage](null)
- [ ] ember-jquery [homepage](https://github.com/topaxi/ember-jquery#readme)
- [x] [PR](https://github.com/miguelcobain/ember-leaflet/pull/163) ember-leaflet [homepage](http://www.ember-leaflet.com/)
- [ ] ember-leaflet-google-mutant-layer [homepage](https://github.com/dio-el-claire/ember-leaflet-google-mutant-layer#readme)
- [ ] ember-leaflet-heatmap [homepage](https://github.com/willviles/ember-leaflet-heatmap#readme)
- [ ] ember-leaflet-heatmap-layer [homepage](https://github.com/dio-el-claire/ember-leaflet-heatmap-layer#readme)
- [ ] ember-leaflet-marker-cluster [homepage](https://github.com/canufeel/ember-leaflet-marker-cluster#readme)
- [ ] ember-maskmoney [homepage](https://github.com/clairton/ember-maskmoney#readme)
- [ ] ember-masonry-grid [homepage](https://github.com/gmurphey/ember-masonry-grid#readme)
- [ ] [PR](https://github.com/mike-north/ember-materialize-shim/pull/90) ember-materialize-shim [homepage](https://github.com/levanto-financial/ember-materialize-shim#readme)
- [x] [PR](https://github.com/kolybasov/ember-medium-editor/pull/2) ember-medium-editor [homepage](https://github.com/kolybasov/ember-medium-editor#readme)
- [ ] ember-medium-editor-button [homepage](https://github.com/willviles/ember-medium-editor-button#readme)
- [ ] ember-medium-editor-insert [homepage](https://github.com/willviles/ember-medium-editor-insert#readme)
- [ ] ember-mousetrap [homepage](https://github.com/idobata/ember-mousetrap#readme)
- [ ] [PR](https://github.com/tomdale/ember-network/pull/20) ember-network [homepage](https://github.com/tomdale/ember-network#readme)
- [ ] ember-nvd3-shim [homepage](https://github.com/mike-north/ember-nvd3-shim#readme)
- [x] [PR](https://github.com/tim-evans/ember-page-title/pull/70) ember-page-title [homepage](tim-evans/ember-page-title)
- [x] [PR](https://github.com/miguelcobain/ember-paper/pull/730) ember-paper [homepage](https://github.com/miguelcobain/ember-paper#readme)
- [ ] ember-parsley-js [homepage](https://github.com/apipemc/ember-parsley-js#readme)
- [ ] ember-pca-predict [homepage](https://github.com/PrinceCornNM/ember-pca-predict)
- [x] [PR](https://github.com/percy/ember-percy/pull/30/files) ember-percy [homepage](https://github.com/percy/ember-percy#readme)
- [ ] ember-perfectscroll [homepage](https://github.com/imanhodjaev/ember-perfect-scroll#readme)
- [ ] ember-phoenix [homepage](https://github.com/mike-north/ember-phoenix#readme)
- [ ] ember-photoswipe [homepage](https://github.com/kaermorchen/ember-photoswipe#readme)
- [ ] ember-picturefill [homepage](https://github.com/alexlafroscia/ember-picturefill#readme)
- [x] [PR](https://github.com/edgycircle/ember-pikaday/pull/157) ember-pikaday [homepage](https://github.com/edgycircle/ember-pikaday#readme)
- [ ] ember-pikaday-time [homepage](https://github.com/Inkstone-Inc/ember-pikaday-time#readme)
- [x] [PR](https://github.com/tim-evans/ember-plupload/pull/112) ember-plupload [homepage](https://github.com/tim-evans/ember-plupload#readme)
- [ ] ember-query-builder [homepage](https://github.com/offirgolan/ember-query-builder#readme)
- [ ] ember-range-slider [homepage](https://github.com/collectrium/ember-range-slider#readme)
- [ ] ember-remodal [homepage](https://github.com/sethbrasile/ember-remodal#readme)
- [ ] ember-run-raf [homepage](https://github.com/runspired/ember-run-raf)
- [x] [PR](https://github.com/willviles/ember-scrollmagic/pull/3) ember-scrollmagic [homepage](https://github.com/willviles/ember-scrollmagic#readme)
- [ ] ember-service-worker-cache-rendered [homepage](https://github.com/PrinceCornNM/ember-service-worker-cache-rendered#readme)
- [ ] ember-shepherd [homepage](http://shipshapecode.github.io/ember-shepherd/)
- [ ] ember-smooch [homepage](http://davidpett.github.io/ember-smooch/)
- [ ] ember-spectrum-color-picker [homepage](https://github.com/rsschermer/ember-spectrum-color-picker)
- [ ] ember-spin-button [homepage](https://github.com/ivanvanderbyl/ember-spin-button#readme)
- [ ] ember-stickyfill [homepage](http://davidpett.github.io/ember-stickyfill/)
- [ ] ember-ticketfly-accordion [homepage](https://github.com/Ticketfly/ember-ticketfly-accordion#readme)
- [ ] ember-tweenlite [homepage](https://github.com/runspired/ember-tweenlite#readme)
- [ ] ember-typewriter [homepage](https://github.com/shipshapecode/ember-typewriter#readme)
- [x] [NO-PR provided] ember-vivus [homepage](https://github.com/shipshapecode/ember-vivus#readme)
- [ ] ember-web-animations-next-polyfill [homepage](https://github.com/BrianSipple/ember-web-animations-next-polyfill#readme)
- [x] [PR](https://github.com/thoov/ember-websockets/pull/142) ember-websockets [homepage](https://github.com/thoov/ember-websockets#readme)
- [ ] ember-x-editable [homepage](https://github.com/shipshapecode/ember-x-editable#readme)
- [ ] ember-zeroclipboard [homepage](https://github.com/jasonkriss/ember-zeroclipboard#readme)
- [ ] ivy-codemirror [homepage](https://github.com/IvyApp/ivy-codemirror#readme)
- [ ] ivy-videojs [homepage](https://github.com/IvyApp/ivy-videojs#readme)
- [ ] mk-videojs-record [homepage](https://github.com/multicora/mc-videojs-record-ember#readme)
- [x] [PR](https://github.com/cardstack/ember-data-fastboot/pull/11) ember-data-fastboot [homepage](https://github.com/cardstack/ember-data-fastboot#readme)
- [ ] [PR](https://github.com/intercom/ember-href-to/pull/79) ember-href-to

*note: script for ^ https://gist.github.com/stefanpenner/ff5be0c7c2a3aabed49dd00fda8fd461 *

**Comment by simonihmig** [comment]
@stefanpenner where would you want that list to live in? Here in this issue? I worked on migrating a couple of addons, and could list a few that I know of that still need some love ;)

**Comment by stefanpenner** [comment]
> @stefanpenner where would you want that list to live in? Here in this issue?

This issue (just a checklist). I was going to extract this list this morning, but would love a hand (I am quite busy). Do you happen to have any cycles?

**Comment by simonihmig** [comment]
> Do you happen to have any cycles?

I think I should be able to put something together tomorrow!

**Comment by stefanpenner** [comment]
https://emberobserver.com/code-search?codeQuery=process.env.EMBER_CLI_FASTBOOT

**Comment by simonihmig** [comment]
Yeah, I know. See https://github.com/ember-fastboot/ember-cli-fastboot/issues/360#issuecomment-284688058. Unfortunately that list seems to grow over time, from back then 95 addons to now 117... 😩

**Comment by simonihmig** [comment]
@stefanpenner I think we need to merge those as well: https://emberobserver.com/code-search?codeQuery=fastboot-filter-initializers

**Comment by stefanpenner** [comment]
@simonihmig good call, give me a sec.

**Comment by simonihmig** [comment]
Some ongoing PRs:
* https://github.com/ronco/ember-cli-head/pull/21
* https://github.com/html-next/ember-hammertime/pull/34
* https://github.com/html-next/ember-gestures/pull/89

And I think you can remove `ember-cli-fastboot` from that list! 😉

**Comment by simonihmig** [comment]
@stefanpenner nice little script! 👌 I wonder if we could come up w/ something similar that takes this list and automatically creates an issue on each github repo? That way we could build awareness amongst the respective addon authors. Put links to @kratiahuja's guide and other helpful information into the template used to create the issue text...

I started some migrations by myself just to prepare addons that we use in our own app, but given the size of that list, and the fact that it actually grew quite a bit during the last weeks, I think we have to inform addon authors sooner than later, and rely on them making the necessary changes!

**Comment by stefanpenner** [comment]
> @stefanpenner nice little script! 👌 I wonder if we could come up w/ something similar that takes this list and automatically creates an issue on each github repo?

Totally, and this would in-general be a super useful tool. I unfortunately don't have the time, but would love it to exist (hint hint, if you have time).

**Comment by simonihmig** [comment]
> hint hint, if you have time

Hm, I can give it a try over the weekend I hope...

**Comment by simonihmig** [comment]
Here is another PR I just created: https://github.com/cardstack/ember-data-fastboot/pull/11

The addon was missing in the list, because it did not have the `fastboot-filter-initializers` as its own dependencies (relying on ember-cli-fastboot to be present)...

**Comment by buschtoens** [comment]
https://github.com/tim-evans/ember-page-title/pull/70

Feel free to remove this comment after adding the PR. :slightly_smiling_face:

**Comment by simonihmig** [comment]
@stefanpenner finally got this tool finished, did underestimate the effort a bit, but anyway here it is: 
https://github.com/simonihmig/fastboot-migration-issue-creator

It uses the same logic as your shell script to fetch addons that need to be fixed, based on the emberobserver.com code search API, then checks if there is any existing open issue/PR containing "FastBoot 1.0" (skips those), and then creates an issue like this one: https://github.com/simonihmig/fastboot-migration-issue-creator-dummy-addon/issues/6

If you see something that should be changed here, feel free to create an issue on its repo. Otherwise if that looks fine, I could run that script to create all those issues. If you prefer that to be done with some others github account, that would be ok for me as well...

cc @kratiahuja

**Comment by stefanpenner** [comment]
@simonihmig very cool. I will try and give it a whirl this weekend!

**Comment by kratiahuja** [comment]
@simonihmig super awesome! will give it a try!

**Comment by simonihmig** [comment]
@kratiahuja @stefanpenner Sure, play with it. Just make sure to either use the `-t` or `-d` flag! ;) Just updated the Readme to make this more clear...

**Comment by simonihmig** [comment]
Btw, ember-x-editable-addon can be removed, that doesn't even exist!?

**Comment by kratiahuja** [comment]
@simonihmig updated the issue with the correct homepage.

**Comment by simonihmig** [comment]
@kratiahuja but we have that twice :) I think the -addon one can really be removed!
![image](https://cloud.githubusercontent.com/assets/1325249/26524666/fa082544-433a-11e7-9acd-9c106ddd40fe.png)

**Comment by kratiahuja** [comment]
Aah ok, I'll remove that on. Thanks for pointing it out. We have one less to go ;)

**Comment by mazondo** [comment]
PR's that address this issue that I had to submit in the process of updating our app:

ember-href-to: https://github.com/intercom/ember-href-to/pull/79
ember-cli-swiper: https://github.com/Suven/ember-cli-swiper/pull/56
ember-cli-daterangepicker: https://github.com/outdoorsy/ember-cli-daterangepicker

the daterange picker add-on has some additional non-fastboot related changes in it that we needed.  Once we go live with this I'll make a PR - we just need to add some test coverage/confirm it's ready to merge.  Should be good to go for anyone who needs quick fb rc.1 support tho 👍

**Comment by tsubomii** [comment]
Sent PR for 
ember-add-to-homescreen https://github.com/mike-north/ember-add-to-homescreen/pull/79/files
 ember-algolia https://github.com/PrinceCornNM/ember-algolia/pull/2

**Comment by jasonmit** [comment]
ember-cli-moment-shim and ember-cli-showdown have been updated

**Comment by tsubomii** [comment]
ember-algolia PR is merged.

**Comment by simonihmig** [comment]
Add a PR for ember-cli-mirage: https://github.com/samselikoff/ember-cli-mirage/pull/1098

**Comment by tsubomii** [comment]
@stefanpenner @kratiahuja  One more PR for ember-aupac-typeahead https://github.com/aupac/ember-aupac-typeahead/pull/53

**Comment by tsubomii** [comment]
@stefanpenner @kratiahuja 
One more PR ember-background-video :  https://github.com/this-dot/ember-background-video/pull/1

**Comment by tsubomii** [comment]
@stefanpenner @kratiahuja more PRs
ember-baremetrics-calendar : https://github.com/davewasmer/ember-baremetrics-calendar/pull/10
ember-bootstrap-datepicker : https://github.com/topaxi/ember-bootstrap-datepicker/pull/1
ember-background-video PR is merged.

**Comment by tsubomii** [comment]
@stefanpenner @kratiahuja one more
https://github.com/mike-north/ember-c3-shim/pull/91

**Comment by kategengler** [comment]
Rerunning the above searches & limiting the results to addons that rank in the top 100, yields the following list (addon name, ranking, homepage):

- [x] [PR](https://github.com/samselikoff/ember-cli-mirage/pull/1098) ember-cli-mirage, 13, [homepage](https://github.com/samselikoff/ember-cli-mirage)
- [ ] ember-pikaday, 39, [homepage](https://github.com/edgycircle/ember-pikaday)
- [ ] ember-websockets, 56, [homepage](https://github.com/thoov/ember-websockets)
- [ ] ember-paper, 69, [homepage](https://github.com/miguelcobain/ember-paper)
- [x] [PR](https://github.com/jasonmit/ember-cli-moment-shim/pull/137/files) ember-cli-moment-shim, 79, [homepage](http://github.com/jasonmit/ember-cli-moment-shim)
- [ ] ember-cli-showdown, 93, [homepage](https://github.com/gcollazo/ember-cli-showdown)

**Comment by kratiahuja** [comment]
@kategengler Awesome! thanks a bunch for this insightful info.

**Comment by josemarluedke** [comment]
`ember-cli-daterangepicker` can be checked off.

**Comment by simonc** [comment]
`ember-cli-bootstrap-sassy` can be checked off too for lifegadget/ember-cli-bootstrap-sassy#49 was merged.

**Comment by rwwagner90** [comment]
Hey guys, I see a lot of my addons are on here 😞 . Would someone please be able to help me out with how to do this with ember-cli-node-assets, rather than using `treeForVendor` manually or do I need to do it manually now? I have generally done it like this https://github.com/shipshapecode/ember-flatpickr/blob/master/index.js#L12

**Comment by kratiahuja** [comment]
@rwwagner90 you could use the `processTree` property of `ember-cli-node-assets` to process the non fastboot compatible libraries using `fastboot-transform`. I can do a PR against `ember-flatpickr` to show you an example.

**Comment by rwwagner90** [comment]
@kratiahuja that would be great, thanks!

**Comment by kratiahuja** [comment]
@rwwagner90 I have a PR here: https://github.com/shipshapecode/ember-flatpickr/pull/182 (Please make sure to test it)

**Comment by rwwagner90** [comment]
ember-headroom, ember-flatpickr, and ember-vivus should be good to go, and can be checked off the list.

**Comment by leizhao4** [comment]
PR for ember-inputmask: https://github.com/pzuraq/ember-inputmask/pull/39

I hope it's the correct way of fixing it because I'm not too familiar with FastBoot. If someone could help review the PR then it would be awesome.

Thanks for the great work!

**Comment by josemarluedke** [comment]
PR for ember-cli-bugsnag binhums/ember-cli-bugsnag#77.

**Comment by josemarluedke** [comment]
PR for ember-pikaday edgycircle/ember-pikaday#157

**Comment by devotox** [comment]
https://github.com/ahmadsoe/ember-offline/pull/4
https://github.com/ember-engines/ember-engines/pull/444
https://github.com/sethwebster/ember-cli-new-version/pull/35

Couple of PRS out to work with Fastboot for these libraries

**Comment by kellyselden** [comment]
v1.0.0 is live and we have a sufficient mass of updated addons that the rest can copy.

**Comment by Redsandro** [comment]
Can someone help me with this? In the examples, it seems awfully simple. But I seem err on every attempt.

https://github.com/gmurphey/ember-masonry-grid/issues/58#issuecomment-373759770

Disclaimer: I've never developed plugins for ember, just trying to get this to work so I can update my old fastboot.
