### ISSUE TITLE
Unskip `ember-cli-head` usage test

### ISSUE THREAD

**Issue by kratiahuja** [ember-fastboot/ember-cli-fastboot#393]
When #369 landed, we did not skipped the `ember-cli-head` addon tests in `ember-cli-fastboot`. This was because the addon requires to be updated per the fastboot migration guide. There is a [PR in ember-cli-head](https://github.com/ronco/ember-cli-head/pull/21) when landed and released , we should skip the tests [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/test/head-content-test.js#L9)

**Comment by mirague** [comment]
@kratiahuja Does this cause:

```
FastBoot build no longer supports /Users/mirage/Projects/myproject/node_modules/ember-cli-head/app/(instance-)?initializers/browser structure. Please refer to www.ember-fastboot.com for a migration path.
```

I got this after upgrading from `1.0.0-beta.18` to `1.0.0-beta.19`/`1.0.0-rc.1`.

The error message is not very helpful in that the link contains no migration support.

**Comment by kratiahuja** [comment]
@mirague: please see this issue https://github.com/ember-fastboot/ember-cli-fastboot/issues/387

**Comment by kratiahuja** [comment]
Test is unskipped.
