### ISSUE TITLE
Prepare for FastBoot 1.0

### ISSUE THREAD

**Issue by kratiahuja** [ember-fastboot/ember-cli-fastboot#396]
We are nearing FastBoot 1.0 since the build and serve issues have been resolved. Here are the things we need to do:

# Must-have
- [x] Cut a `beta` branch since `master` is now for RC and contains the simplified build which makes addons backward incompatible.
- [x] Throw a deprecation message in `beta` branch if someone is using `ember fastboot`
- [x] Release a new version of beta (`ember-cli-fastboot@1.0.0-beta.19`)
- [x] Remove `ember fastboot` command tests from `master` (same as https://github.com/ember-fastboot/ember-cli-fastboot/issues/394)
- [x] Enable appveyor for `master`
- [x] Unskip `ember-cli-head` test
- [x] Migrate some addons to prepare for FastBoot 1.0. Bare minimum the addons listed here: http://ember-fastboot.com/docs/user-guide#useful-ember-addons-for-fastboot (#387) 
- [x] Update README
- [x] Update website (PR: https://github.com/ember-fastboot/fastboot-website/pull/70)
- [x] Release `ember-cli-fastboot@rc.1` 🎉 
- [x] Release `ember-cli-fastboot@1.0`, `fastboot@1.0`, `fastboot-app-server@1.0` etc 🎉 

# Nice to have
- [ ] Move some of the fastboot tests into dummy addon to speed up the test execution. We can keep some for sanity here since `ember-cli-addon-tests` tests against canary version of ember.

cc: @stefanpenner @danmcclain @tomdale @tsubomii @rwjblue @arjansingh

**Comment by kellyselden** [comment]
v1.0.0 is live!
