### ISSUE TITLE
Issues with storeConfigInMeta being false

### ISSUE THREAD

**Issue by PrinceCornNM** [ember-fastboot/ember-cli-fastboot#409]
It seems like there is a new error for apps using `storeConfigInMeta = false`. I think it has to do with explicitly checking for the meta-tag prior to the code that generates this error: `Uncaught Error: Could not read config from meta tag with name "<app-name>/config/environment".`

**Comment by stefanpenner** [comment]
What version of fastboot/ember/ember-cli are you using?

**Comment by kratiahuja** [comment]
I just tried this with ember-cli-fastboot@rc.1 build and ember-cli 2.13 and it worked for me. 

This is what the `config/environment` AMD module looked for me:
```js
define('my-app/config/environment', ['ember'], function(Ember) {
  if (typeof FastBoot !== 'undefined') {
return FastBoot.config();
} else {
var prefix = 'my-app';
try {
  var metaName = prefix + '/config/environment';
  var rawConfig = document.querySelector('meta[name="' + metaName + '"]').getAttribute('content');
  var config = JSON.parse(unescape(rawConfig));

  var exports = { 'default': config };

  Object.defineProperty(exports, '__esModule', { value: true });

  return exports;
}
catch(err) {
  throw new Error('Could not read config from meta tag with name "' + metaName + '".');
}

}
});
```

**Comment by kratiahuja** [comment]
I think I understand the bug here. For `storeConfigInMeta` as false, we don't want to read from the meta tag and instead have something like this:

```js
define('my-app/config/environment', ['ember'], function(Ember) {
  var exports = {'default': {"modulePrefix":"my-app","environment":"development","rootURL":"/","locationType":"auto","EmberENV":{"FEATURES":{},"EXTEND_PROTOTYPES":{"Date":false}},"APP":{"name":"my-app","version":"0.0.0+8209f419"},"exportApplicationGlobal":true}};Object.defineProperty(exports, '__esModule', {value: true});return exports;
});
```

Therefore, fastboot will need to check if this option is turned on and then respect that for browser. Will need to dig a bit deeper how `storeConfigInMeta` works. The issue is in this line: https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L88
