### ISSUE TITLE
Upgrading from 1.0.0-beta.19 to v1.0.0-rc.2 does baaaad things

### ISSUE THREAD

**Issue by jakeleboeuf** [ember-fastboot/ember-cli-fastboot#414]
I'll dig into this further and provide some more details in the morning, but reverting back to `1.0.0-beta.19` resolved my issues :) 

`infinite rendering invalidation detected`

**Comment by stefanpenner** [comment]
>  provide some more details in the morning 

Will gladly reopen when these are provided, but without this issues isn't at all actionable. (and i want to fix your problems)
