### ISSUE TITLE
Ajax initializer prevents users to override `_ajaxRequest`

### ISSUE THREAD

**Issue by cibernox** [ember-fastboot/ember-cli-fastboot#419]
After a pretty big debugging session I found why [this PR into ember-fetch](https://github.com/stefanpenner/ember-fetch/pull/31) is not working in fastboot with a weird error message: `Cannot read property 'then' of undefined`

It turns out that this initializer is replacing the `_ajaxRequest` method on every adapter by the `ajax:node` utility.

```
application.inject('adapter', '_ajaxRequest', 'ajax:node');
```

Essentially, both addons are fighting. One wants ember-data to use the `fetch` API as network adapter, and the other is precluding it.

What could be an approach that allows both to coexist. I do think that the goal of using `fetch` as network interface is the right one in the long term.

/cc @kratiahuja @stefanpenner @nlfurniss

**Comment by kratiahuja** [comment]
I will look at this tonight and reply back here.

**Comment by kratiahuja** [comment]
> What could be an approach that allows both to coexist. I do think that the goal of using fetch as network interface is the right one in the long term.

@cibernox One approach would be: create an fastboot initializer in `ember-fetch` that runs _after_ [this](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/fastboot/initializers/ajax.js) and that replaces the `_ajaxRequest`. this way you can use ember-data + fetch + fastboot 🎉 . However, there is a caveat to that. Now for apps that are using `ember-fetch` for `Ember.$.ajax` replacement in fastboot will also use `fetch` for ember-data requests. Therefore, you should make sure the `_ajaxRequest` replacement in `ember-fetch` is optional via some config or something or via the mixin setting some property.

I agree `fetch` api as network adapter is the right one in the long term. However, we should make sure it is a opt-in for now.

**Comment by cibernox** [comment]
That could work. I wonder if there is something in ember-data itself that we can do to make this less awkward. By example, setting the headers was rather complicated because traditionally in ember data they were set using the `beforeSend` function, which has no counterpart in fetch and it's also hard (impossible?) to introspect to provide transform into a fetch-compatible options object.

**Comment by kratiahuja** [comment]
@cibernox ideally if ember-data gave a network interface it is easy to hook najax, fetch etc.

I am going to close this since it doesn't seem to be related `ember-cli-fastboot` and `fetch` is an opt in at this point.
