### ISSUE TITLE
Semantics of treeForFastBoot

### ISSUE THREAD

**Issue by simonihmig** [ember-fastboot/ember-cli-fastboot#420]
Just stumbled upon this when looking at the code: I am not sure if the current semantics of the `treeForFastBoot` hook are what users would expect, or makes most sense.

Currently any addon's `/fastboot` tree is taken ([source](https://github.com/ember-fastboot/ember-cli-fastboot/blob/6bc10810c40cb0d08aa9078d4dc7d9f6953984b2/index.js#L120-L121)) and the (optional) output of calling `treeForFastBoot` on the addon is merged *on top* of that ([source](https://github.com/ember-fastboot/ember-cli-fastboot/blob/6bc10810c40cb0d08aa9078d4dc7d9f6953984b2/index.js#L128)). Which is ok when you want to modify/extend the tree. But using a Funnel in that hook seems to be pointless.

My understanding of the other ember-cli's `treeFor` hooks like `treeForPublic` is that only the tree that those hooks return is taken into account (so Funnel works). And I feel the same semantics should probably be also applied to the `treeForFastBoot` hook, shouldn't they?

Happy to add a PR if we can agree on this!

**Comment by kratiahuja** [comment]
What happens when you use a funnel? This hook simply returns a `broccoli` tree so I imagine funnel should also work.

**Comment by simonihmig** [comment]
@kratiahuja actually I have not tested this, but by looking at the code I would say that because the whole ("unfunneled") tree is added regardless of the output of the hook (see https://github.com/ember-fastboot/ember-cli-fastboot/blob/6bc10810c40cb0d08aa9078d4dc7d9f6953984b2/index.js#L120-L121), you would still end up with having the whole tree, even when the hook returns a reduced (funneled) one!? 

Since the whole, unfunneled tree is part of the `mergeTrees` call, you cannot remove anything from it. Or do I miss something?

**Comment by simonihmig** [comment]
Btw, the output of the hook is assigned to `additionalFastBootTree`, so that says it all, doesn't it? :)

**Comment by rwjblue** [comment]
I addressed this in #423
