### ISSUE TITLE
`generateAssetMap` must be `true` in app ember-cli-build.js

### ISSUE THREAD

**Issue by mixonic** [ember-fastboot/ember-cli-fastboot#424]
I upgraded from ember-cli-fastboot 1.0.0-beta.12 to 1.0.0-rc.2. I'm using fastboot-app-server to run the app at version 1.0.0-rc.5 (unchanged).

After upgrading builds were successful, but the fastboot-app-server failed with:

```js
Error: ENOENT: no such file or directory, open '/app/dist/assets/vendor.js'
     at Error (native)
     at Object.fs.openSync (fs.js:641:18)
     at Object.fs.readFileSync (fs.js:509:33)
     at /app/node_modules/fastboot/src/ember-app.js:141:27
     at Array.forEach (native)
     at EmberApp.loadAppFiles (/app/node_modules/fastboot/src/ember-app.js:139:21)
     at EmberApp.retrieveSandboxedApp (/app/node_modules/fastboot/src/ember-app.js:187:10)
     at new EmberApp (/app/node_modules/fastboot/src/ember-app.js:50:21)
     at FastBoot._buildEmberApp (/app/node_modules/fastboot/src/index.js:114:17)
     at new FastBoot (/app/node_modules/fastboot/src/index.js:52:10)
```

In the `dist/package.json` of my app the `vendorFiles` value did not have a fingerprint, but the actual production build files were of course fingerprinted.

Some debugging yielded the following:

* `this.assetMapEnabled` is only `true` if `generateAssetMap` is `true` for broccoli-asset-rev [[source](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/lib/broccoli/fastboot-config.js#L27)].
* By `this.assetMapEnabled` being `true` perhaps [this line would log an error instead of fail silently](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/lib/broccoli/fastboot-config.js#L134).

With this in mind I changed `ember-cli-build.js` in my app to the following:

```js
  var app = new EmberApp(defaults, {
    fingerprint: {
      generateAssetMap: true
    }
  });
```

Which (kind of surprisingly?) caused my `dist/package.json` to have the correct fingerprinted values. Thus fixing my server.

It seems odd that the app server must have this flag set instead of ember-cli-fastboot defaulting it? Or at the least it is undocumented?

**Comment by kratiahuja** [comment]
@mixonic 
I agree it should error out. I think it undocumented. @scottmessinger was going to put it in the docs.

I am fine with defaulting it to be true if the fingeprint is enabled. 

The reason why we need this is flag was to be able to read the fingerprinted assets and put them in the manifest.

**Comment by kratiahuja** [comment]
I will look into this a bit more to see how it was working in beta.12. I might have messed up something when i chnaged it to use `generateAssetMap`.

**Comment by andreasschacht** [comment]
I also figured out, that it doesn't work with a fingerprinted assetmap.
That means the following will **NOT** work:
```js
var app = new EmberApp(defaults, {
    fingerprint: {
      generateAssetMap: true,
      fingerprintAssetMap: true
    }
  });
```

**Comment by jobackman** [comment]
Thank god, I thought I was alone with this error 😭

I've got the exact same error as @mixonic, and the same fix worked for me 🎉

I first noticed it when I upgraded  from v1.0.0-beta.18 to v1.0.0-beta.19, it only occured on production builds when I ran my fastboot-app-server, and it has been so since then at any version > v1.0.0-beta.18

**Comment by kratiahuja** [comment]
My apologies. I didn't get a chance to look at this. I will take a stab at it this week and see what I might have messed up and avoid this breaking change.

**Comment by kratiahuja** [comment]
Ok finally tracked this down. #112 attempted to fix this issue but it doesn't seem to be present in beta or rc builds. Hence apps needed to explicitly set it. I have re-introduced the fix with setting it by `generateAssetMap` to be `true` by default. We already had an error if it didn't generate it but it was set to warning.

**Comment by kratiahuja** [comment]
Fix is already in PR.
