### ISSUE TITLE
Not currently possible to debug in Node 8

### ISSUE THREAD

**Issue by mansona** [ember-fastboot/ember-cli-fastboot#428]
Because of the requirement to use node-inspector (and the [incompatibility with --inspect](https://github.com/ember-fastboot/ember-cli-fastboot#incompatibility-with-node---inspect)) we have now been prevented from using Node 8 because node-inspector is incompatible with Node 8 https://github.com/node-inspector/node-inspector/issues/1010

Now it makes us more dependent on the the [issue linked in the readme](https://github.com/nodejs/node/issues/7593)

**Comment by kratiahuja** [comment]
@mansona would it be possible for you to send a PR to update the readme?

**Comment by mansona** [comment]
Sure, I suppose 😂 

I am just not too sure of a) what you want it to say and b) the merit of updating the readme to say "sorry no can do Node 8"

The reason it doesn't feel right to me is that Node 8.x is going to be LTS in a few months and my preference would just be for us to track the problem in an issue like this. If you still think I should try to summarise this in the Readme just say so and I'm happy to give it a whirl 👍

**Comment by kratiahuja** [comment]
I think the limitation to use Node 8 is from debugging purposes. Therefore, it won't hurt to put an FYI so that users know about it and link the relevant inspector ticket.

**Comment by mansona** [comment]
Ok so it seems like there has been some movement on https://github.com/nodejs/node/issues/7593 and testing this issue on node-nightly I was able to pause in the native `node --inspect` debugger: 

```
➜ node-nightly --version
v9.0.0-nightly201708155f31d54720
➜ node-nightly --inspect node_modules/ember-cli/bin/ember s
```

![Image of ember fastboot example paused in deugger](https://user-images.githubusercontent.com/594890/29365377-b7a54c3e-828e-11e7-8e62-634533f30fbc.png)

I know this isn't ideal for anyone who wants to use `node --inspect` natively but hopefully this is going to be merged into the v8.x branch 👍

**Comment by mansona** [comment]
Aha!! 🎉  

It seems like this has already been merged and released into the v8.4 branch: https://github.com/nodejs/node/pull/14811

I was able to successfully debug the fastboot execution with the following: 

```
➜  github-fastboot-example git:(master) ✗ node -v
v8.4.0
➜  github-fastboot-example git:(master) ✗ node --inspect node_modules/ember-cli/bin/ember s
```

I guess all that is left is to update the documentation and say "if you want to inspect then use v8.4+"

**Comment by rwjblue** [comment]
Awesome news @mansona! We should definitely get the docs updated, this is so much easier now! 🎉

**Comment by mansona** [comment]
@rwjblue since it was so much easier I figured I'd spend a bit of time and update the docs 😉
