### ISSUE TITLE
how to import jquery dependencies on latest rc in ember-cli-build.js ?

### ISSUE THREAD

**Issue by Zorig** [ember-fastboot/ember-cli-fastboot#430]
first of all thank you for doing such an amazing addon for ember app. I updated `ember-cli-fastboot` and get JQuery not defined with `foundation.min.js` then looked over readme, [this](https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c), and [this file](https://github.com/ember-fastboot/ember-cli-fastboot/issues/387) before it was using `env.EMBER_CLI_FASTBOOT` variable which is now removed, so how can i use it

**Comment by danmcclain** [comment]
This issue is tracking addon compatibility and has steps to migrate away from the environment variable: https://github.com/ember-fastboot/ember-cli-fastboot/issues/387

**Comment by kratiahuja** [comment]
If it is an app there is using that environment variable, please create an in-repo addon and move the imports there.

**Comment by kratiahuja** [comment]
Closing this. @Zorig please feel free to reopen if you have questions.

**Comment by Zorig** [comment]
@kratiahuja thanks, is it possible to implement **ember-cli-foundation-6-sass**?

**Comment by kratiahuja** [comment]
@zorig: yes. There are numerous examples of addons already converted. Please follow #387.
