### ISSUE TITLE
FastBoot undefined in ember-cli-build.js

### ISSUE THREAD

**Issue by edance** [ember-fastboot/ember-cli-fastboot#433]
Not sure if this is an issue. Might be more like a question.

I used to have this code in my `ember-cli-build.js`. This was removed in RC1:
```javascript
if (!process.env.EMBER_CLI_FASTBOOT) {
  app.import('bower_components/lib.js');
}
```

I am trying to upgrade to the newest version and the readme states that a global variable `FastBoot` is available in `ember-cli-build.js` However the code below does not work:

```javascript
if (typeof FastBoot === 'undefined') {
  app.import('bower_components/lib.js');
}
```

Should `FastBoot` be defined here? Is there a different hook that I should be using? If so, what file is this hook in?

I am using `1.0.0-rc.4`. Thanks!

**Comment by stefanpenner** [comment]
> Should FastBoot be defined here?

I don't believe so. I believe that should only be defined in the app code (not build code)

**Comment by edance** [comment]
How would I go about not including bower components without building an addon?

**Comment by kratiahuja** [comment]
@edance Currently that is not possible unless you create an in-repo addon. I have an RFC to expose an API to allow apps to do this as well. But the alternative is create an in-repo addon in your app and do the import there.

**Comment by danmcclain** [comment]
See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387, there is a gist with migration steps

**Comment by kratiahuja** [comment]
Going to close this since there is an alternative currently. We are working on a more declarative API for the making it less friction for the app.

**Comment by sebyx07** [comment]
copy the js file to the public directory ex public/js/file.js, then use a script src from index.html. Or import the file from a cdn directly
