### ISSUE TITLE
my ember production app is cant recognize some jquery plugin and bootstrap javascript

### ISSUE THREAD

**Issue by cahyowhy** [ember-fastboot/ember-cli-fastboot#438]
hey i just wanna make a production ready with ember fastboot app, the problem is when i push to my heroku repository the log said "bootstrap need jquery" then i delete the app.import('vendor/bootstrap.js'); from ember cli build now the problem is said "TypeError: Cannot read property 'fn' of undefined". the question is how to include jquery plugin and bootstrap javascript to my ember fastboot app, cause i really need that for my dom manipulation. All ajax call is done by ember-fetch

**Comment by kratiahuja** [comment]
Hey @cahyowhy FastBoot does not support Jquery or any dom manipulation via jquery. It has a minimal DOm API that it uses to serialize your template. Moreover, fastboot does not run certain component hooks that are meant for dom manipulation (example didInsertElement). Therefore, you cannot simply include bootstrap in Node. My suggestion is to check out the user guide on ember-fastboot.com to understand how you can make bootstrap run only in browser and do dom manipulation only in hooks that don't run in Node.

**Comment by cahyowhy** [comment]
@kratiahuja can you provide a clear answer? iam really new about this add on

**Comment by cahyowhy** [comment]
@kratiahuja iam calling the jquery plugin via ember build, how to selectively import the package if the app runing via fastboot server?

**Comment by kratiahuja** [comment]
Can you show me a clear example of what You are doing? If I have that, I can provide you with a more concrete answer. Also have you checked out ember-fastboot.com?

**Comment by cahyowhy** [comment]
this is my ember-cli-build file

[https://gist.github.com/cahyowhy/38c5ccab46b46e66b04deeb6cf1cf3ed](url)

im trying to include bootstrap.js and some jquery plugin to my ember application.
but its doesnt work the 3rd plugin doesnt include in my ember app when i visit localhost:4200?fastboot=false.

```
var app = new EmberApp(defaults, {
    'ember-cli-bootstrap-sassy': {
      'js': false
    },
    treeForVendor(defaultTree) {
      var browserVendorLib = new Funnel('bower_components/rateYo/min/jquery.rateyo.min.js');
      browserVendorLib = map(browserVendorLib, (content) => `if (typeof FastBoot === 'undefined') { ${content} }`);

      return new mergeTrees([defaultTree, browserVendorLib]);
    },
    included() {
      // this file will be loaded in FastBoot but will not be eval'd
      if (!process.env.EMBER_CLI_FASTBOOT) {
        app.import('vendor/bootstrap.js');
        app.import('bower_components/jquery-ui/jquery-ui.min.js');
        app.import('bower_components/rateYo/min/jquery.rateyo.min.js');
        app.import('bower_components/slick-carousel/slick/slick.js');
        app.import('bower_components/jquery-slimscroll/jquery.slimscroll.js');
      }
    }
  });
```

**Comment by cahyowhy** [comment]
i just make my custom add on and this is my addon index.js
```
/* eslint-env node */
'use strict';

var map = require('broccoli-stew').map;
var Funnel     = require('broccoli-funnel');
var mergeTrees = require('broccoli-merge-trees');

module.exports = {
  name: 'slick-template',
  treeForVendor: function (defaultTree) {
    var browserVendorLib = new Funnel('bower_components/slick-carousel/');
    browserVendorLib = map(browserVendorLib, (content) => `if (typeof FastBoot === 'undefined') { ${content} }`);
    return new mergeTrees([defaultTree, browserVendorLib]);
  },
  included: function (app) {
    this._super.included(app);
    app.import('bower_components/slick-carousel/slick/slick.js');
  }
};
```
this is work when i add queryparams ?fastboot=false, but its show error whne ?fastboot=true. How to load this plugin via fastboot server ?
thanks for your concern..

**Comment by kratiahuja** [comment]
@cahyowhy As mentioned earlier, jQuery is not defined in the FastBoot server so you cannot load those libraries in Node. I highly recommend to read the user guide on the fastboot website to understand how things work in FastBoot: http://ember-fastboot.com/docs/user-guide 

If you want to load these libraries only in browser (with ?fastboot=true), I created a sample app here to show you an example of how to load `slick.js` : https://github.com/kratiahuja/sample-in-repo-fastboot/commit/8874fe35575ddfa8d3f63dd9b3b7e65aa2b7dc68 

Please follow the example in there. 

I am going to close this since this isn't an issue/bug but more of a question. Please feel free to ping in the ember community fastboot slack channel if you have more questions. In future, we will add a declarative API to make it easier for you to load browser only compatible libraries in your vendor.js
