### ISSUE TITLE
setProperties() not working correctly under Fastboot in Node 7

### ISSUE THREAD

**Issue by BlueRaja** [ember-fastboot/ember-cli-fastboot#440]
Repro code:
```
a.setProperties({b: 'b'});
a.setProperties({});
```

Expected result:
a is `{ b: 'b' }`

Actual result
a is `{}`

Only seems to happen in Fastboot using node 7 (specifically, 7.7.3) - it works correctly in node 6.  Once the non-fastboot page loads, `a` is set correctly.

We're running an older version of fastboot (`ember-cli-fastboot 1.0.0-beta.14`, `ember-cli 2.11.0`) so this may have been fixed already, but I didn't see anything like it in the issues.

**Comment by kratiahuja** [comment]
Could you please try the latest release?

**Comment by BlueRaja** [comment]
We were able to repro this morning using that exact code but now we're not, with no changes.  Best I can tell there are gremlins in the system.  Sorry!

**Comment by tomdale** [comment]
@BlueRaja Thanks for the report, glad it was just gremlins!
