### ISSUE TITLE
App not being served by FastBoot when rootURL is set

### ISSUE THREAD

**Issue by claire-lee** [ember-fastboot/ember-cli-fastboot#441]
I'm attempting to upgrade to FastBoot 1.0.0-rc.5 with Ember CLI version 2.12.2. The app's rootURL configuration is set to something other than the default, e.g. '/test/'. When I run the app using `ember serve`, it's not being served by FastBoot.

It looks like this is because `broccoliHeader['url']` does not match `req.serveUrl` in the check  [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/f0863abadd8226951dd6218b6c68cc44f6ee02a0/index.js#L241). `req.serveUrl` includes the rootURL but `broccoliHeader['url']` does not, e.g.
```
broccoliHeader['url']: /index.html
req.serveUrl: /test/index.html
```
and this causes the app to be served normally. (I also confirmed that the value of `enableFastBootServe` was true)

Additionally, I'm now unable to run the app using the `ember fastboot` command as I get an error message saying it's been removed.

**Comment by kratiahuja** [comment]
Hi @claire-lee Thanks for the bug report! This seems an edge case we surely missed out on. I'll take a look at this and hopefully send a PR out later tonight.

**Comment by kratiahuja** [comment]
I think just checking for `req.serveUrl` is defined should suffice enough for us to know if we should serve the base page via fastboot.
