### ISSUE TITLE
issue with chalk dependency in 1.0

### ISSUE THREAD

**Issue by kellyselden** [ember-fastboot/ember-cli-fastboot#451]
```
  Error: Command failed: ember i ember-cli-fastboot@1.0.0

  Cannot read property 'close' of undefined

  TypeError: Cannot read property 'close' of undefined
      at Object.<anonymous> (tmp/my-app/node_modules/fastboot/node_modules/chalk/index.js:65:74)
      at require (internal/module.js:12:17)
      at Object.<anonymous> (tmp/my-app/node_modules/fastboot/src/ember-app.js:5:15)
      at checkExecSyncError (child_process.js:468:13)
      at execSync (child_process.js:508:13)
      at run (test/acceptance/index-test.js:45:10)
      at initMyApp (test/acceptance/index-test.js:104:5)
      at init (test/acceptance/index-test.js:57:3)
      at Context.<anonymous> (test/acceptance/index-test.js:363:9)
```

https://github.com/kellyselden/fastboot-pool/pull/45
https://travis-ci.org/kellyselden/fastboot-pool/builds/255401023#L1637-L1649

**Comment by kratiahuja** [comment]
```
~/work/fastboot-work/1.0/my-app master
❯ ember i ember-cli-fastboot@1.0.0
WARNING: Ember CLI is using the global NPM, but your NPM version has not yet been verified to work with the current Ember CLI release.
NPM: Installed ember-cli-fastboot@1.0.0
Installed addon package.
```

@kellyselden Just tried this locally and it seems to work for me. I am using npm@5.x. Any reason why travis is using npm@2 for you?

**Comment by kellyselden** [comment]
It should be using yarn https://travis-ci.org/kellyselden/fastboot-pool/builds/255401023#L524

**Comment by kratiahuja** [comment]
I tried the exact same steps in your test locally and it works for me.  Can you reproduce it locally? I can take a look at it then.

**Comment by kellyselden** [comment]
I reproduced locally. yarn 0.27.5, node 7.10.1. make sure `/tmp` is gone so it creates a fresh app for testing. Then run `yarn test`. This should show up in the logs:

```
  fastboot-pool tmp: ember new my-app -sg --yarn +1ms
  fastboot-pool tmp/my-app: ember i ember-cli-fastboot@1.0.0 +1m
```

If you see this:

```
  fastboot-pool my-app: early return +1ms
```

It is using a cached install.

**Comment by kellyselden** [comment]
BTW CI was using node 4, so node version shouldn't be a factor.

**Comment by kellyselden** [comment]
Just tried the new master, still broken.

**Comment by kratiahuja** [comment]
Ok will dig into this deeper now that there is a reproduction.

**Comment by kellyselden** [comment]
This was a chalk mismatch issue, and has since rectified itself. Thanks.

**Comment by MichalBryxi** [comment]
![wisdom_of_the_ancients](https://user-images.githubusercontent.com/847473/75585913-15aed000-5a6b-11ea-9188-75d5e033ac74.png)
