### ISSUE TITLE
Should we release new version?

### ISSUE THREAD

**Issue by kellyselden** [ember-fastboot/ember-cli-fastboot#452]
Lots of dependencies got major version updates in #446. Should we release a 1.0.1 or 1.1.0 now so that we aren't surprised in a future release?

`chalk` was included in the major version updates, so it may resolve #451.

**Comment by kratiahuja** [comment]
I am fine with 1.0.1.

**Comment by kellyselden** [comment]
@kratiahuja Do you mind releasing, or adding me to npm releasers?

**Comment by kratiahuja** [comment]
Sure, I'll release and add you to npm owner list by EOD.

**Comment by kellyselden** [comment]
Note: this does not fix #451

**Comment by kratiahuja** [comment]
Ok will dig into #451 later tonight and report back tomorrow.

**Comment by kratiahuja** [comment]
@kellyselden ember-cli-fastboot@1.0.1 is released
