### ISSUE TITLE
vendorFiles in manifest contains nulls

### ISSUE THREAD

**Issue by marcoow** [ember-fastboot/ember-cli-fastboot#453]
I'm experiencing a strange bug with `vendorFiles` in `dist/package.json` containing `null`s. So what we're doing is:

```js
updateFastBootManifest(manifest) {
  readEnv();
  let locales = required('MWEB_AVAILABLE_LOCALES', { split: true });

  locales.forEach((file) => {
    manifest.vendorFiles.unshift(`assets/intl/translations/${file}.js`);
  });

  return manifest;
}
```

but then `package.json` contains this:

```json
"vendorFiles": [
  null,
  null,
  null,
  null,
  null,
  "assets/vendor-54cbaa284df1362f9c89aa65a85259a8.js",
  "ember-fetch/fastboot-fetch-08106afddb87faa0588f5028789deed2.js"
]
```

I'm pretty sure that this worked fine before upgrading to the 1.0 release (haven't verified that's causing it yet).

**Comment by kratiahuja** [comment]
@marcoow seems like a bug in how you are require the files? Can you put in a minimal reproduction?

**Comment by marcoow** [comment]
The problem is that the `assets/intl/translations/${file}.js` files are not in the `assetMap.json` because we add them after calling `app.toTree()` which I believe is when the asset map gets written.

I'm closing this as I think this is a problem with how we add the files to the app tree actually.

Thanks for the quick reply and your great work on FastBoot!

**Comment by marcoow** [comment]
I think this is actually a valid bug. When there are non-fingerprinted files that are not present in `assetMap.json` (e.g. because they were excluded from fingerprinting via [broccoli-asset-rev](https://github.com/rickharrison/broccoli-asset-rev)'s `exclude` option) those file's paths should be used as they are. I guess [this block](https://github.com/ember-fastboot/ember-cli-fastboot/blob/f0863abadd8226951dd6218b6c68cc44f6ee02a0/lib/broccoli/fastboot-config.js#L170) should be changed to

```js
if (rewrittenAssets) {
  // update the vendor file with the fingerprinted file
  let rewrittenVendorFiles = manifest['vendorFiles'].map(file => rewrittenAssets.assets[file] || file);
  manifest['vendorFiles'] = rewrittenVendorFiles;

  // update the app files array with fingerprinted files
  let rewrittenAppFiles = manifest['appFiles'].map(file => rewrittenAssets.assets[file] || file);
  manifest['appFiles'] = rewrittenAppFiles;
}
```

(important part being the `|| file`). I'm happy to submit a PR, just not sure what the best way to test this is.
