### ISSUE TITLE
Ember error substrates

### ISSUE THREAD

**Issue by ampatspell** [ember-fastboot/ember-cli-fastboot#458]
I'm working on ember app which does some things only in fastboot. If route's model hook in fastboot is rejected, I would like return fastboot rendered error substrate and pass serialized error to client.

Can this be done?

Right now I'm resolving with null model, putting error in shoebox and rendering nothing, then looking up serialized model or error in shoebox and resolving/rejecting on client. 

The downside is that error conditions now render blank page.

**Comment by kratiahuja** [comment]
Can you define what you mean by "fastboot rendered error substate"?

**Comment by ampatspell** [comment]
Oh, sorry for not being clear.

I was wondering if it is possible to get ember in fastboot to render error substrate -- error page like `routename-error.hbs` or `application-error.hbs`.

My usecase is like this:

```
// route/something.js
export default Route.extend({
  model() {
    return this.get('something').load();
  }
});
```

where `something.load()` might reject with error. 

In browser that will render `something-error.hbs` but in fastboot it depends only on `resilient` setting but in any case this won't render aforementioned error page.

I would like to figure out if it is possible to get fastboot to render and respond with error page.

**Comment by kratiahuja** [comment]
Why can't you use the error event and transitionTo the error route? I don't think then you need to worry about the `resilient` flag since your `visit` request will succeed.

**Comment by kratiahuja** [comment]
Going to close this since you can create an error route and define an error event. Please feel free to reopen if this doesn't work for you.
