### ISSUE TITLE
`this.app` undefined when used from an addon

### ISSUE THREAD

**Issue by tchak** [ember-fastboot/ember-cli-fastboot#466]
`ember-cli-staticboot` demonstrate this issue with latest `ember-cli-fastboot` https://github.com/robwebdev/ember-cli-staticboot/issues/30

Here is the code where it is happening:
https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L166

I am not familiar enough with addon internals to realise if `ember-cli-staticboot` is doing something that it should not or if this is just a use case that was not expected.

**Comment by kratiahuja** [comment]
Going to close this per discussion in #467. ember-cli-staticboot shouldn't depend on this addon.
