### ISSUE TITLE
Backward compatibility with process.env.EMBER_CLI_FASTBOOT

### ISSUE THREAD

**Issue by mabab** [ember-fastboot/ember-cli-fastboot#517]
How to leave backward compatibility with the old addons who used the process.env.EMBER_CLI_FASTBOOT ?

Exemple index.js of old addon:
/* jshint node: true */
'use strict';

module.exports = {
  name: 'ember-cli-bootstrap-datepicker',

  included: function(app) {
    this._super.included(app);

    if (process.env.EMBER_CLI_FASTBOOT !== 'true') {
      app.import(app.bowerDirectory + '/bootstrap-datepicker/dist/js/bootstrap-datepicker.js');
      app.import(app.bowerDirectory + '/bootstrap-datepicker/dist/css/bootstrap-datepicker.css');
    }
  }
};

**Comment by kratiahuja** [comment]
@mabab Please follow the migration cheatsheet here: https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c 

Since this is a question rather than a bug report, I am going to close this. Please reach out in the #-fastboot community channel.
