### ISSUE TITLE
It's not possible to extend application FastBoot config via addon hook fastbootConfigTree

### ISSUE THREAD

**Issue by SergeAstapov** [ember-fastboot/ember-cli-fastboot#543]
As of version 1.1.0 ember-cli-fastboot allows to have a map of config names in dist/package.json in order to support engines (see #513 for details).

I would like to be able to extend host app config at build time with some extra env variables that are available only in FastBoot mode, but are not exposed in client side application.

I'm not able to extend config provided by ember-cli-fastboot because `Object.assign` is used which does not support recursive merge.

@kratiahuja was it made this way by design or we can use something like `lodash.merge`?

I'm referring to this line https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/lib/broccoli/fastboot-config.js#L97

If this cane be improved - I'll submit PR shortly.

**Comment by kratiahuja** [comment]
AFAIU `Object.assign` should do a recursive merge. Do you have an example in hand?

**Comment by rwjblue** [comment]
`Object.assign` is not a deep merge, it is only top level keys of each of the arguments.

**Comment by SergeAstapov** [comment]
Created #544 to address this and do deep merge.

**Comment by rwjblue** [comment]
closed by #544
