### ISSUE TITLE
Generate Request ID

### ISSUE THREAD

**Issue by tomdale** [ember-fastboot/ember-cli-fastboot#56]
Given that multiple application instances can be running in parallel, each producing log output, we should generate a unique ID per application instance, and use that unique ID to identify all log output.

We should probably also make the ID available inside the app, as developers may want to use it. Though, now that I think about it, we may want to have a generic `request` service that contains metadata about the incoming request. Eventually we will want to support things like cookie auth, so that may be a good place for things like cookie info, requester IP, request ID, etc.

**Comment by sandstrom** [comment]
Not sure if it's the same type of id, but if it is aligning with Rails et. al. would be nice. Those are ~32 chars, alphanum + dashes and the header is named `X-Request-Id`.

https://www.npmjs.com/package/request-id
http://api.rubyonrails.org/classes/ActionDispatch/RequestId.html

**Comment by tomdale** [comment]
@sandstrom Sounds good, wanna PR it? ☺️

**Comment by sandstrom** [comment]
I don't have time now, sorry! :smile:

**Comment by jasonmit** [comment]
I can pick this up.  My idea was to just generate a UUID inside of the RequestObject constructor.  Would that be sufficient or is there more to it?

**Comment by sandstrom** [comment]
@jasonmit UUID works.

For `X-Request-Id` on the client-side the outbound XHR-requests should include the header plus a unique value (UUID).

A server implementation should first check if `X-Request-Id` is present in the incoming request. If so, it should not generate any value of its own, instead it should simply mirror it back in the response headers (and will probably put it into its logs too). If none is present in the incoming headers it should generate a value and put it into its outgoing headers.

In this case I guess the code will run on the backend (but will represent a http-client), so it should generate them for headers of outbound http requests.

**Comment by stefanpenner** [comment]
@jasonmit wanna take this one up still?

**Comment by tomdale** [comment]
Now that we expose the request to the Ember app, it's pretty easy to add this yourself. I think this can be closed.
