### ISSUE TITLE
Input text is gone when user enters text before JavaScript is downloaded - best practice?

### ISSUE THREAD

**Issue by Kuzirashi** [ember-fastboot/ember-cli-fastboot#560]
Hey guys, when I'm using FastBoot and user enters text into inputs in my form (BEFORE JAVASCRIPT IS LOADED), and then tries to submit it - Ember empties input elements.

I'd like to ask for best practice how to deal with such situations? Should I show input fields in `didInsertElement` hooks? Or is it possible to show some kind of spinner before Ember is fully loaded?

Thanks, really appreciate the work which has been done over the years in Ember!

**Comment by kratiahuja** [comment]
You could show a spinner when rendering the page in FastBoot. You could wrap your form with a fastboot check itself. Take a look here: http://ember-fastboot.com/docs/user-guide#use-model-hooks-to-defer-rendering

**Comment by Kuzirashi** [comment]
Thank you for your response @kratiahuja. I have a question however:

> You could wrap your form with a fastboot check itself. 

Does this mean that the could would be evaluated twice? First - by FastBoot - and omitted and then - by the browser - and rendered if I wrap the form code with FastBoot check?

**Comment by simonihmig** [comment]
FWIW, I was just working on a solution to the same problem. So far I followed this approach:
1. collect all input values just before the static DOM is destroyed
2. "rehydrate" the inputs after the first (browser) render, by reassigning the `value`, and focussing the previously focused input (if any)
3. render all forms in FastBoot like `<form onsubmit="alert('Please wait message'); return false;">`, which will prevent form submission until the Ember app has taken over.

I have already prepared this as an in-repo addon, might publish this if it makes sense to you, and after some cleanup/docs etc.

**Comment by Kuzirashi** [comment]
> I have already prepared this as an in-repo addon, might publish this if it makes sense to you, and after some cleanup/docs etc.

Would this make sense to me? : o It would save my life...

**Comment by Kuzirashi** [comment]
@simonihmig making sure that you receive notification, because seems like... we would love this if you'd publish this addon! :heart:

**Comment by simonihmig** [comment]
@Kuzirashi Here you go: https://github.com/kaliber5/ember-fastboot-form-rehydration

It's at an early stage, definitely needs some more love (i.e. tests), but feel free to try it out! 
It does not cover case 3 mentioned in https://github.com/ember-fastboot/ember-cli-fastboot/issues/560#issuecomment-351093606, as we did that in our app code itself. But might be possible to even integrate that into the addon as well sometime... 

Feedback certainly welcome, but let's move that to its own repo! ;)

**Comment by rwjblue** [comment]
Another approach (simpler in implementation, but objectively worse to end users due to delay) is to render controls in a disabled state from within fastboot.
