### ISSUE TITLE
Disable Incompatible Dependencies

### ISSUE THREAD

**Issue by tomdale** [ember-fastboot/ember-cli-fastboot#57]
We need some way to tell Ember CLI not to include addons that rely on `document`/other DOM features in the build output for FastBoot, since they cause the app to raise an exception on boot.

**Comment by danmcclain** [comment]
This should be considered done since we can use the ENV variable in the ember-cli-build.js

**Comment by tomdale** [comment]
@danmcclain Is this covered in the docs? If not, I'm happy to close this once it is.

**Comment by danmcclain** [comment]
@tomdale: I'll check, if not, I'll document and reference this issue :+1:
