### ISSUE TITLE
Ember 3.1 + fastboot + ember-fetch hangs

### ISSUE THREAD

**Issue by rwwagner90** [ember-fastboot/ember-cli-fastboot#575]
I don't have specifics or reproduction steps yet, but I converted my app to use ember-fetch awhile back, to remove jQuery, and after updating to Ember 3.1 beta, my `this.store.findAll` calls were just hanging. Switching back to using jQuery seems to fix the issue, so I'm not sure if the bug is with fastboot or ember-fetch, but I would love some help figuring it out!

**Comment by 0xadada** [comment]
did you setup the `ember-fetch` adapter mixin [per the `ember-fetch` docs](https://github.com/ember-cli/ember-fetch/#use-with-fastboot)

Then you'll need to config fastboot to noop the ajax initializer.
```js
// fastboot/initializers/ajax.js (you'll need to create a fastboot dir)
export default {
  name: 'ajax-service',
  initialize() {
    /* noop
     * This is to override Fastboot's initializer which prevents ember-fetch from working
     * https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/fastboot/initializers/ajax.js
     */
  }
};
```

**Comment by rwwagner90** [comment]
@0xadada yep, this is a confirmed issue in ember-fetch https://github.com/ember-cli/ember-fetch/issues/106 I suppose I should probably close this one.
