### ISSUE TITLE
FOUC in lazy engines + fastboot

### ISSUE THREAD

**Issue by Duder-onomy** [ember-fastboot/ember-cli-fastboot#590]
Using version ember-engines version 0.5.16, and the nearly latest fastboot 1.1.3
There is a FOUC when a lazy engines routes is being served by fastboot. 

The engine.css is not loaded until after ember boots and revives the page:
![image](https://user-images.githubusercontent.com/1612785/37999147-644e29e6-31d6-11e8-986e-34b58489f552.png)

It would be nice to get that engine.css injected into the head when rending a lazy engine.

I also opened this in the ember-engines repo to provide more visibility.
https://github.com/ember-engines/ember-engines/issues/530

**Comment by Duder-onomy** [comment]
From this issue: https://github.com/ember-engines/ember-engines/issues/530 This seems to be related to fastboot more than ember-engines?

**Comment by Duder-onomy** [comment]
This is still a legitimate issue. People have been talking about it in ember slack.

**Comment by Duder-onomy** [comment]
Turning off javascript this can be reproduced 100% of the time....

**Comment by kratiahuja** [comment]
engine.css added in index.html is done by engines and not fastboot. FastBoot simply loads the contents in Node. Is there a reproduction?

**Comment by Duder-onomy** [comment]
Thanks for responding. 
You can repro it on any fastboot app with lazy engines. 

I opened this in ember-engines: https://github.com/ember-engines/ember-engines/issues/530

But they pointed me this way.

**Comment by Duder-onomy** [comment]
I think I found the right spot to push on this, Ember asset loader does nothing when in node/fastboot land

https://github.com/ember-engines/ember-asset-loader/blob/master/addon/loaders/utilities.js#L33

Total bummer. Gonna close this and see if I can push on that repo some more.
