### ISSUE TITLE
How to deal with fastboot directory in module unification 

### ISSUE THREAD

**Issue by ryanto** [ember-fastboot/ember-cli-fastboot#658]
Currently, the `fastboot/` directory in an Ember application is compiled into a JS file that only gets included in the server side build generated by FastBoot. During the last FastBoot meeting a question came up about how to deal with these files once Ember moves to MU.

A possible solution here could involve removing support for the `fastboot/` directory. This would mean the host app would be responsible for determining which code should run server side by using the FastBoot's `isFastboot` or `typeof FastBoot === 'undefined'`. This approach would allow us to remove the separate FastBoot build file.

I took a look a few addons that are using the `fastboot/` directory.

* https://github.com/cardstack/ember-data-fastboot/blob/master/fastboot/instance-initializers/ember-data-fastboot.js
* https://github.com/ember-cli/ember-fetch/blob/master/fastboot/instance-initializers/setup-fetch.js
* https://github.com/embermap/ember-data-storefront/blob/master/fastboot/instance-initializers/ember-data-storefront.js

It looks like all of these initializers could exist as client side app initializers using the FastBoot's `isFastBoot`.  I'm wondering if anyone has any examples of FastBoot initializers that couldn't exist as client side initializers.

There's also a question about how to deal with node modules that get required server side. And the ergonomics of how to wrap an entire module in an `typeof FastBoot` check. A benefit of using the `fastboot/` directory is that you don't have to think about any of that.

cc @kratiahuja @rwjblue @tomdale

**Comment by ryanto** [comment]
@stefanpenner Rob mentioned you might have input on this too.

**Comment by xg-wang** [comment]
MU support is dropped 😢
