### ISSUE TITLE
Issue with fastboot after upgrading to ember 3.9

### ISSUE THREAD

**Issue by lucacorti** [ember-fastboot/ember-cli-fastboot#686]
I'm getting this error from fastboot while running in production (fastboot-app-server), this does not happen in local development:

```
Error: Cannot find module 'abortcontroller-polyfill/dist/cjs-ponyfill'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.require (node_modules/fastboot/src/ember-app.js:130:18)
    at a.callback (ember-fetch/fetch-fastboot-5e5d008c8b65b0ac116f7635d0c6c6b9.js:1:24)
    at a.exports (assets/vendor-21774982fde9f3d01e619c23b73298da.js:19:21)
    at a._reify (assets/vendor-21774982fde9f3d01e619c23b73298da.js:22:35)
    at a.reify (assets/vendor-21774982fde9f3d01e619c23b73298da.js:21:23)
    at a.exports (assets/vendor-21774982fde9f3d01e619c23b73298da.js:18:84)
```

**Comment by lucacorti** [comment]
Looks related to https://github.com/ember-cli/ember-fetch/issues/184

**Comment by kiwiupover** [comment]
What version of ember-data are you using? If ember-data 3.9.0 there is a
fix coming in 3.9.1 which should be released this week.

Cheers
Dave

**Comment by lucacorti** [comment]
@kiwiupover I'm having the same issue with 3.9.1

**Comment by igorT** [comment]
@kiwiupover This seems slightly different from the ED 3.9.0 issue, but still like it's coming from fetch.

**Comment by kiwiupover** [comment]
@lucacorti add ember-fetch to your app. 

`ember install ember-fetch`

**Comment by lucacorti** [comment]
@kiwiupover I have `ember-fetch` as a devDependency in my `package.json`

**Comment by rwjblue** [comment]
Can you provide a reproduction repo? It would help in debugging...

**Comment by lucacorti** [comment]
@rwjblue I'm having issues reproducing this in a brand new project.

The issue manifests itself only for my project and only in `fastboot-app-server` on Linux, not when running with `ember s` locally on macOS. A brand new project with ember new from ember-cli@3.9.0 does not exhibit the same behavior in `fastboot-app-server`.

I guess this is triggered by something else in my project, probably some other dependency.

**Comment by rwjblue** [comment]
@xg-wang - I recall this error, but not the specific resolution. Do you happen to remember?

**Comment by xg-wang** [comment]
@rwjblue Are you saying this issue https://github.com/ember-cli/ember-fetch/issues/115?
@lucacorti Have you installed node_modules within `fastboot-app-server`? I'm asking because if not this error will occur https://github.com/ember-fastboot/fastboot/pull/200#discussion_r229138457.

**Comment by lucacorti** [comment]
@xg-wang Just to check if I'm getting this right, am I supposed to run yarn or npm install in the `dist` directory which contains the build of my application?

I do install `fastboot-app-server` in a different folder with its own deps already and everything used to work. Is this only needed for `ember-fetch`?

**Comment by xg-wang** [comment]
@lucacorti Yes you should run `yarn` or `npm install` in `dist`. This is not well documented (@kratiahuja can you confirm?) and applies to all addons that support fastboot and require extra dependencies.

**Comment by lucacorti** [comment]
@xg-wang yes the issue looks exactely like mine, but after running yarn in dist, and having depdendencies in dist/node_modules (including abortcontroller-polyfill) I have exactely the same error with fastboot.

**Comment by lucacorti** [comment]
@xg-wang @rwjblue I just noticed `fastboot-app-server` depends on `fastboot` 1.x while `ember-cli-fastboot` is using `fastboot` 2.x. Not sure if this helps, but some fix for this is mentioned in the changelog for fastboot 2.0.0 (ember-fastboot/fastboot#200) so I guess `fastboot-app-server` might need a fastboot bump?

**Comment by lucacorti** [comment]
I submitted a PR to `fastboot-app-server` bumping `fastboot` to 2.0 and f`astboot-express-middleware` to 1.2.0. This solves the issue for me.

**Comment by arschmitz** [comment]
After updating my app to fastboot 2.x im running into this as well

**Comment by lucacorti** [comment]
FastbootAppServer 2.0.0 is out with ember-fastboot/fastboot-app-server#102 merges. I tested this, in production and everything works as expected, so I'm closing this.

Thanks to everyone for the help.
