### ISSUE TITLE
HTTP status codes for routes

### ISSUE THREAD

**Issue by topaxi** [ember-fastboot/ember-cli-fastboot#69]
A Ember route should be able to somehow set a HTTP status code with fastboot.

I see mostly four cases:
- `404` for a `this.route('notfound', { path: '/*path' })` catch-all 404 handler
- `404` for a error route which fails because something was not found (ember-data, ajax, etc.)
- `403` authentication errors on routes (for example through ember-simple-auth)
- `500` any non-handled error route/action, I guess

**Comment by rwjblue** [comment]
Also need to handle redirects (301,302).

**Comment by tomdale** [comment]
404s should already be supported. I agree with the other stuff, but it strongly impacts the programming model so I don't want to rush it. I think this is probably a nice-to-have for 1.0. I would love it if you could write up an RFC-like proposal.

**Comment by danmcclain** [comment]
This has been handled with the `response` object in the `fastboot` service
