### ISSUE TITLE
Ability to disable with config

### ISSUE THREAD

**Issue by mehulkar** [ember-fastboot/ember-cli-fastboot#698]
There are currently two ways to disable fastboot: query param and uninstalling the module. 
I would like to be able disable fastboot entirely by setting a app level config instead (this could be extended to an environment variable in development as well).

**Comment by SergeAstapov** [comment]
@mehulkar according to [readme](https://github.com/ember-fastboot/ember-cli-fastboot#disabling-fastboot-with-ember-serve):

> You can even disable serving fastboot with `ember serve` using an environment flag: `FASTBOOT_DISABLED=true ember serve`. If you have disabled building fastboot assets using the same flag as described [here](https://github.com/ember-fastboot/ember-cli-fastboot#double-build-times-and-no-incremental-builds), remember to also disable serving fastboot assets when using `ember serve`.

you may set `process.env.FASTBOOT_DISABLED=true` in ember-cli-build.js via something like
```js
if (!('FASTBOOT_DISABLED' in process.env)) {
  process.env.FASTBOOT_DISABLED = EmberApp.env() !== 'production';
}
```

Does it sound like "environment variable in development" or something close enough to it?

**Comment by mehulkar** [comment]
hah, that's great! haven't tried it yet, but can close this issue in that case. Thanks!
