### ISSUE TITLE
Build failure using version 2.2.0 - missing 'broccoli-file-creator' dependency

### ISSUE THREAD

**Issue by lupestro** [ember-fastboot/ember-cli-fastboot#724]
In 2.2.0, require('broccoli-file-creator') was added to /index.js but not to package.json. Using this version in my application produces the following error:
```
Cannot find module 'broccoli-file-creator'
```
When I force the version back to 2.1.1 in my package.json, the error no longer occurs.  (I debated submitting the issue or making a PR, but things are hectic this evening and I didn't want this to slip through the cracks.)

**Comment by rwjblue** [comment]
Eeck! Sorry about that!
