### ISSUE TITLE
Memory leak in fastboot server mode

### ISSUE THREAD

**Issue by victor-stone** [ember-fastboot/ember-cli-fastboot#73]
Steps - (NB: I'm installing my fork but only to get the project to build and generate html)

`ember new testlinkto`
`cd testlinkto`
`bower install components/ember#canary components/ember-data#canary --save`
`npm install express`
`npm install glob`
`npm install ember-fastboot-server`
`ember install artistechmedia/ember-cli-fastboot.git#master`
`ember fastboot:build`

At this point if you want to use a server script like [this one](https://raw.githubusercontent.com/victor-stone/fb-test/master/server) that prints out the memory/heap allocation. 

`node --expose-gc server`

And then hit it with [a few 100 curl statements](https://raw.githubusercontent.com/victor-stone/fb-test/master/curlbomb)  you'll note that the heap stays pretty stable with no growth after the a gc.

BUT if you add some #link-to components to app/templates/application.hbs

`{{#link-to index}}homepage{{/link-to}}`
`{{#link-to index}}homepage{{/link-to}}`

then you'll see that heap gives up about 2MB per link-to which is devastating if you have nav-bars/menus with a few dozen links.

**Comment by tomdale** [comment]
@victor-stone Sounds like the memory leak is within Ember itself.

1. What version of Ember was this with?
2. Would you mind filing an issue on the emberjs/ember.js repo?

**Comment by victor-stone** [comment]
wups - missed your first reply - doesn't really matter b/c by Jan my Ember work env was long gone and I had to move on to another solution - by Jan having no idea what vers I was last Oct I'd be hard pressed to file with emberjs without a browser based reproducible case.
