### ISSUE TITLE
Support loading sourcemaps for better error stack traces in Node.

### ISSUE THREAD

**Issue by aghassemi** [ember-fastboot/ember-cli-fastboot#735]
Currently error stacks for any issues on the server are from bundles js files.

It would be great load sourcemaps in node and have error stacks be replaced by sorucemap information. It might be possible to integrate https://github.com/evanw/node-source-map-support our of the box for this.

**Comment by dnalagatla** [comment]
@aghassemi can we close this issue, as I remember the issue in your case was the Source-maps were not getting created during build time. 

FastBoot currently installs source maps for debugging - https://github.com/ember-fastboot/fastboot/blob/cf0f451e7e675c45be2b088480dff62d7866c9ae/src/sandbox.js#L5

**Comment by aghassemi** [comment]
Yep
