### ISSUE TITLE
fastboot.isFastBoot is undefined when FastBoot is available

### ISSUE THREAD

**Issue by runspired** [ember-fastboot/ember-cli-fastboot#742]
It appears we have a race condition for the global as we're seeing a situation in which accessing the `fastboot.isFastBoot` property gives us `false` even though `typeof FastBoot !== 'undefined'` is `true`, suggesting the property on the service is cached prior to the presence of the global.

**Comment by runspired** [comment]
This turned out to be an issue where the injected Fastboot wasn't quite what we thought it was.

**Comment by rwjblue** [comment]
How do we reproduce (in order to fix)?

**Comment by runspired** [comment]
@rwjblue we don’t

**Comment by adambedford** [comment]
I'm having this issue too. @runspired How did you resolve this in your implementation?

**Comment by adambedford** [comment]
Never mind 🤦 The property is `isFastBoot`, not `isFastboot`
