### ISSUE TITLE
Update Shoebox Documentation

### ISSUE THREAD

**Issue by burritoIand** [ember-fastboot/ember-cli-fastboot#761]
Recently while implementing fastboot (ember-cli-fastboot 2.2.2), I read through the current documentation and followed instructions to use the shoebox to fetch data within the node side of things.

I ended up encountering an issue where when retrieving shoebox content within the browser, the serialization format was incorrect, caused by storing a reference to an object that included mutations from the serializer. After discussing and getting help from @runspired it was tracked down, but additionally he gave a more current example of how to use the shoebox in a route, utilizing the adapter instead of the route model hook itself.

It would be helpful for the next person if the documentation were updated to include this snippet as a method of implementing the shoebox:
```
  cacheKeyFor([, model, id]) {
    return (model.modelName && id) ? `${model.modelName}-${id}` : 'default-store';
  }

  async findRecord() {
    const key = this.cacheKeyFor(arguments);

    if (this.fastboot.isFastBoot) {
      let result = await super.findRecord(...arguments);

      // must deep-copy to avoid serialization formatting issues.
      result = JSON.parse(JSON.stringify(result));

      this.fastboot.shoebox.put(key, result);

      return result;
    }

    let result = this.fastboot.shoebox.retrieve(key);

    if (!result) {
      result = await super.findRecord(...arguments);
    }

     // must deep-copy to avoid serialization formatting issues.
     return JSON.parse(JSON.stringify(result));
  }
```

**Comment by kratiahuja** [comment]
Thanks for the feedback @burritoIand . Would you like to send a PR for the same?

**Comment by burritoIand** [comment]
@kratiahuja https://github.com/ember-fastboot/ember-cli-fastboot/pull/762

**Comment by burritoIand** [comment]
merged https://github.com/ember-fastboot/ember-cli-fastboot/pull/762
