### ISSUE TITLE
Support Meta Tags (OpenGraph / Twitter Cards)

### ISSUE THREAD

**Issue by tomdale** [ember-fastboot/ember-cli-fastboot#77]
Right now there's no way for an Ember application to put content into the `<meta>` tag of a page. This is necessary for FastBoot, especially for OpenGraph and Twitter cards. This will likely require an extension to Ember itself, although maybe we can do something as a quick workaround until a full solution is in place.

**Comment by rwjblue** [comment]
@tomdale - It is possible and currently done by at least [one addon](http://www.emberaddons.com/?query=meta) :smile:.  https://github.com/tildeio/ember-cli-fastboot/pull/66 (which supercedes https://github.com/tildeio/ember-cli-fastboot/pull/49) adds support here and https://github.com/ember-fastboot/ember-fastboot-server/pull/1 adds support to ember-fastboot-server.

**Comment by tomdale** [comment]
@rwjblue Ah nice, thank you!

**Comment by tomdale** [comment]
@ronco is working on this in https://github.com/tildeio/ember-cli-fastboot/pull/66 but is blocked

**Comment by ronco** [comment]
#114 + [server #15](https://github.com/ember-fastboot/ember-fastboot-server/pull/15) and [ember-cli-head](https://github.com/ronco/ember-cli-head) will meet this need until Ember provides full document population.
