### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by josemarluedke** [ember-fastboot/ember-cli-fastboot#777]
It would be awesome if we got a new release out with the latest changes. I'm mainly looking for FastBoot v3 compatibility.

**Comment by kiwiupover** [comment]
@josemarluedke We will discuss a new release in the fastboot team meeting tomorrow Aug 20, 2020. I don't see any issues with a cutting a new release.

**Comment by rwjblue** [comment]
I think we did this?
