### ISSUE TITLE
Should FastBoot call willRender and didRender?

### ISSUE THREAD

**Issue by nag5000** [ember-fastboot/ember-cli-fastboot#784]
According to the [docs](https://github.com/ember-fastboot/ember-cli-fastboot/tree/b723a43c3d1223af101b2ef4e821d85ff7185c81#no-didinsertelement), yes, it should. But in my classic component they aren't called in FastBoot environment. The component is simple and rendered correctly (in both environments - fastboot and browser), without exceptions.

ember-cli-fastboot 2.2.3
ember 3.8.3

**Comment by rwjblue** [comment]
They should not be called in FastBoot, the documentation is in error (I've submitted #798 to fix).
