### ISSUE TITLE
Expose FastBoot service

### ISSUE THREAD

**Issue by tomdale** [ember-fastboot/ember-cli-fastboot#79]
I wanted to jot down some thoughts about how we expose FastBoot functionality and additional data into Ember apps. The idea is pretty simple: expose a `fastboot` service that can house whatever APIs we need to expose to app and addon developers over time.

### `fastboot` Service

Inject it like any service:

```js
import inject from "ember-service/inject";

export default Route.extend({
  fastboot: inject(),

  init() {
    let fastboot = this.get('fastboot');
  }
});
```

### Environment Detection

```js
export default Service.extend({
  fastboot: inject(),
  matchMedia(query) {
    if (this.get('fastboot.isFastBoot')) {
      return false;
    } else {
      return window.matchMedia(query).matches;
    }
  }
});
```

### Cookies

Cookies sent by the requester's browser.

```js
export default Service.extend({
  fastboot: inject(),
  isAuthorized() {
    let cookies = this.get('fastboot.cookies');
    return this.verifyAuthToken(cookies.authToken);
  }
});
```

### Headers

Headers attached to the HTTP request for this route.

```js
export default Service.extend({
  fastboot: inject(),
  isAuthorized() {
    let headers = this.get('fastboot.headers');
    return this.verifyAuthToken(headers['X-Auth-Token']);
  }
});
```

**Comment by ef4** [comment]
Would this be a service in core Ember or in the fastboot addon?

Because I can imagine a lot of addons that want to check isFastBoot without forcing a dependency on the fastboot addon.

**Comment by tomdale** [comment]
@ef4: In the FastBoot addon. I'm thinking about proposing an "optional" flag for service injections so they don't blow up if not available:

```js
  fastboot: inject({ optional: true })
```

**Comment by ef4** [comment]
Optional injection would be great.

**Comment by rwjblue** [comment]
I like the idea of a service, but I believe we will still need something available at module eval time (service is only useful at runtime from an object instantiated by the container).

**Comment by tomdale** [comment]
@rwjblue Can you say more about the evaluation-time use case?

Thanks,
Tom

**Comment by marcoow** [comment]
I guess it would make sense to have a `cookies` service that abstract all interactions with cookies (as sketched in #120) so that the app can always use the same mechanism to read/write cookies regardless of whether it's running in the browser or in the fastboot env?
