### ISSUE TITLE
DEPRECATION: A value was injected implicitly on the '_fastbootInfo' property

### ISSUE THREAD

**Issue by lolmaus** [ember-fastboot/ember-cli-fastboot#819]
Hi!

I'm receiving this deprecation:

> DEPRECATION: A value was injected implicitly on the '_fastbootInfo' property of an instance of <docs-app@service:fastboot::ember223>. Implicit injection is now deprecated, please add an explicit injection for this value. If the injected value is a service, consider using the @service decorator. [deprecation id: implicit-injections] See https://deprecations.emberjs.com/v3.x#toc_implicit-injections for more details.

This appeared after upgrading Ember from 3.23 to 3.26.

I am not touching `_fastbootInfo` in my code and am not using any third-party addons on top of FastBoot.

**Comment by mamiller93** [comment]
Any update on this one?

**Comment by knownasilya** [comment]
Looks like https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/packages/fastboot/src/fastboot-info.js#L41 is set here. Probably need to change how this value is accessed on the fastboot service. Not sure what the best option is. cc @kiwiupover
