### ISSUE TITLE
Use of Ember global triggers deprecation / fails for Ember 4

### ISSUE THREAD

**Issue by simonihmig** [ember-fastboot/ember-cli-fastboot#827]
Direct access of the Ember global [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/2a6ed5d76b00da2106a9ba10f048aa2bef989a80/packages/ember-cli-fastboot/vendor/experimental-render-mode-rehydrate.js#L7-L10) triggers a deprecation in latest Ember versions (3.27+)

**Comment by rwjblue** [comment]
Thank you for reporting!

**Comment by josemarluedke** [comment]
What would be the path to remove the Ember global usage here?

**Comment by mixonic** [comment]
In theory the approach I'm using at https://github.com/emberjs/ember.js/pull/19678/files#r675555766 can be applied here. I'm not sure how undesirable that is.
