### ISSUE TITLE
Cannot read property 'userAgent' of undefined

### ISSUE THREAD

**Issue by teckays** [ember-fastboot/ember-cli-fastboot#83]
`$ ember fastboot --serve-assets`

```
Cannot read property 'userAgent' of undefined
TypeError: Cannot read property 'userAgent' of undefined
    at Object.125.global/document (<anonymous>:121923:53)
    at s (<anonymous>:104896:621)
    at <anonymous>:104896:672
    at Object.106../big-play-button.js (<anonymous>:113849:23)
    at s (<anonymous>:104896:621)
    at <anonymous>:104896:672
    at Object.139.../../src/js/utils/merge-options.js (<anonymous>:123824:15)
    at s (<anonymous>:104896:621)
    at e (<anonymous>:104896:792)
    at <anonymous>:104896:810
```

ideas?

**Comment by tomdale** [comment]
Sounds like video.js (reasonably) assuming it's being loaded in the DOM. We should make an easy way to opt out of including incompatible addons; how are you including video.js?

In the interim, #78 should help a lot with this situation.

**Comment by rtablada** [comment]
:facepalm:

@tomdale any updates on how to opt out?

**Comment by rtablada** [comment]
I have first resolved and made a PR to `ivy-videojs` to only include Video.js libs on asset comp and not vendor.js during the fastboot build.

**Comment by rtablada** [comment]
https://github.com/IvyApp/ivy-videojs/pull/15

**Comment by workmanw** [comment]
Is there any update on this? We're including foundation's js and it's creating the same issue. It seems like one desirable solution would be to import the foundation's JS only for runtime (not at fastboot time). I don't know much about Fastboot's architecture, it's very possible that's easier said than done. It certainly feels like issues like this could be non-starters for many would be Fastboot adopters :(
