### ISSUE TITLE
Beta version breaks ember-body-class route css classes in fastboot mode.

### ISSUE THREAD

**Issue by hoIIer** [ember-fastboot/ember-cli-fastboot#850]
Using the latest 3.2.0-beta.2 version and [ember-body-class](https://github.com/mansona/ember-body-class/issues/43), the route css classes stopped working while in fastboot mode.

![image](https://user-images.githubusercontent.com/230757/130338363-61710dae-b726-493d-834c-d33fc40f4d9e.png)

**Comment by burritoIand** [comment]
realized this may be due to my switch to `{{#in-element}}` from ember-elsewhere :D just discovered it doesn't work in fastboot

**Comment by burritoIand** [comment]
Discovered removing {{in-element}} doesn't resolve

**Comment by hoIIer** [comment]
fixed in latest
