### ISSUE TITLE
htmlSafe function not available in @ember/string but only in fastboot

### ISSUE THREAD

**Issue by mansona** [ember-fastboot/ember-cli-fastboot#855]
When running in fastboot we get an error `TypeError: (0 , _string.htmlSafe) is not a function` but running the same app in the browser doesn't have the same issue. 

I have noticed this issue with the Ember Blog https://github.com/ember-learn/ember-blog and when debugging I can confirm that the object that is injected in place of `@ember/string` does indeed not have the `htmlSafe` function.

In Fastboot: 

<img width="951" alt="Screenshot 2021-08-29 at 07 12 28" src="https://user-images.githubusercontent.com/594890/131240617-460add4c-c814-4b00-a7a9-d38af87aabf5.png">

The exact same code in the browser: 

<img width="859" alt="Screenshot 2021-08-29 at 07 14 04" src="https://user-images.githubusercontent.com/594890/131240644-50b1587d-8ccd-4900-825d-460576b8d09c.png">

--- 

Something else that is odd with this error is that it is a "caught error". For me to hit it in the debugger I had to select "Pause on caught exceptions". It also doesn't register as an error when doing a Prember run which means that we have not been Fasbooting the Ember blog for a while now and we just didn't notice 🙈 

I know this is a known deprecation and with Ember 4.0 it is pretty urgent to fix as quickly as possible but I'm surprised that this is broken in fastboot and working in the browser 🤔

**Comment by hoIIer** [comment]
@mansona did you ever figure this out? I'm seeing same thing after updating deps

**Comment by st-h** [comment]
I have experienced something similar, however in my case it was merely triggering a deprecation. And I was only seeing it in the browser, but not on the fastboot server. While trying to find a solution, someone suggested this issue: https://github.com/emberjs/ember-string/issues/235#issuecomment-1061413761

essentially there are competing implementations in ember-source and `@ember/string` and it looks like nobody knows when which one will be used and under what circumstances.

possibly this issue will also fix that https://github.com/emberjs/ember.js/issues/20383

**Comment by mansona** [comment]
Yes I think this can be closed too 👍
