### ISSUE TITLE
[Embroider] Fastboot enabled apps might fail under embroider-optimized

### ISSUE THREAD

**Issue by BobrImperator** [ember-fastboot/ember-cli-fastboot#924]
Encountered while working on ember-simple-auth. ESA test-suite tests some basic scenarios with fastboot in one of the test apps.
`embroider-optimized` scenario fails. See [Embroider Optimized Test Scenario](https://github.com/mainmatter/ember-simple-auth/actions/runs/5903704407/job/16014244371)

The error points to this file:
https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/packages/ember-cli-fastboot/vendor/experimental-render-mode-rehydrate.js#L4

```
ReferenceError: Ember is not defined
    <anonymous> experimental-render-mode-rehydrate.js:4
    <anonymous> experimental-render-mode-rehydrate.js:33
```

![image](https://github.com/ember-fastboot/ember-cli-fastboot/assets/15948633/7bd04c44-280e-49ec-b1c7-1b4e5dd42ece)

`embroider-safe` scenario works just fine.

https://github.com/mainmatter/ember-simple-auth/pull/2633#event-10130541840

**Comment by villander** [comment]
I have the same error using the following packages

```
 "@embroider/compat": "^3.4.5",
 "@embroider/core": "^3.4.5",
 "@embroider/webpack": "^3.2.2",
 "ember-cli-fastboot": "^4.1.2",
 ```
 
 cc @mansona
